(()=>{
'use strict';
const UCOS=globalThis.SuperApiUCOS;
if(!UCOS||document.querySelector('#ucosOS'))return;

document.title='Super API UCOS';
const state={windows:new Map(),z:50,launcher:false,quick:false,notifications:false,activeApp:null,lab:false,booted:false,installPrompt:null,noticeSeq:0};
const notices=[];
const appRegistry=new Map();
const icon=(glyph,label)=>`<span class="ucos-app-icon" aria-hidden="true">${glyph}</span><span>${label}</span>`;
const safe=v=>{try{return JSON.stringify(v,(_k,x)=>typeof x==='bigint'?String(x):x,2)}catch{return String(v)}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const query=s=>document.querySelector(s);
const nowTime=()=>new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit'}).format(new Date());
const nowDate=()=>new Intl.DateTimeFormat(undefined,{weekday:'short',month:'short',day:'numeric'}).format(new Date());

const style=document.createElement('style');
style.id='ucosShellV3Style';
style.textContent=`
:root{--ucos-bg:#07111d;--ucos-panel:rgba(12,25,41,.88);--ucos-panel-solid:#0d1b2b;--ucos-panel2:#12243a;--ucos-line:#29425f;--ucos-line2:#1b3047;--ucos-text:#eef6ff;--ucos-muted:#91a8bf;--ucos-accent:#63a8ff;--ucos-good:#53dc91;--ucos-warn:#f2c96d;--ucos-bad:#ff7882;--ucos-shadow:0 24px 80px #0009;--ucos-radius:18px}
body.ucos-os-active{overflow:hidden;background:#050b12!important}body.ucos-os-active>header,body.ucos-os-active>main{display:none!important}
#ucosOS{position:fixed;inset:0;z-index:100000;color:var(--ucos-text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto,sans-serif;overflow:hidden;background:radial-gradient(circle at 78% 15%,#14335a 0,transparent 32%),radial-gradient(circle at 12% 92%,#123c37 0,transparent 31%),linear-gradient(145deg,#07101b,#09182a 55%,#07111d)}
#ucosOS *{box-sizing:border-box}#ucosOS button,#ucosOS input,#ucosOS select,#ucosOS textarea{font:inherit;color:inherit}#ucosOS button{cursor:pointer}#ucosOS .hidden{display:none!important}
.ucos-wallpaper{position:absolute;inset:0;background-image:linear-gradient(120deg,rgba(255,255,255,.025) 1px,transparent 1px),linear-gradient(30deg,rgba(255,255,255,.018) 1px,transparent 1px);background-size:56px 56px,72px 72px;pointer-events:none}
.ucos-topbar{position:absolute;left:0;right:0;top:0;height:48px;display:grid;grid-template-columns:1fr minmax(220px,520px) 1fr;align-items:center;padding:0 12px;border-bottom:1px solid #ffffff14;background:#07111dcc;backdrop-filter:blur(22px);z-index:1000}
.ucos-brand{display:flex;align-items:center;gap:9px;min-width:0}.ucos-mark{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:linear-gradient(135deg,#3888f4,#65b5ff);box-shadow:0 0 0 1px #ffffff24,0 8px 25px #1776dd4d;font-weight:900}.ucos-brand strong{font-size:13px}.ucos-brand small{display:block;color:var(--ucos-muted);font-size:10px;margin-top:1px}
.ucos-global-search{height:32px;border:1px solid #38526d;background:#0b1826dd;border-radius:11px;padding:0 12px;display:flex;align-items:center;gap:8px;color:var(--ucos-muted);cursor:pointer;min-width:0}.ucos-global-search span{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ucos-global-search kbd{margin-left:auto;border:1px solid #40566f;border-radius:6px;padding:1px 5px;background:#08131f;color:#9cb3ca;font-size:10px}
.ucos-tray{justify-self:end;display:flex;align-items:center;gap:5px}.ucos-tray-btn{height:32px;border:1px solid transparent;background:transparent;border-radius:9px;padding:0 9px;display:flex;align-items:center;gap:6px}.ucos-tray-btn:hover{background:#ffffff0d;border-color:#ffffff16}.ucos-tray-dot{width:7px;height:7px;border-radius:50%;background:#718499}.ucos-tray-dot.live{background:var(--ucos-good);box-shadow:0 0 0 4px #53dc9120}.ucos-clock{text-align:right;line-height:1.05;font-size:11px;min-width:62px}.ucos-clock b{display:block;font-size:12px}
.ucos-rail{position:absolute;left:0;top:48px;bottom:0;width:72px;border-right:1px solid #ffffff12;background:#07111d9e;backdrop-filter:blur(20px);z-index:800;display:flex;flex-direction:column;align-items:center;padding:14px 8px 12px;gap:8px}.ucos-rail-spacer{flex:1}.ucos-rail-btn,.ucos-dock-btn{border:1px solid transparent;background:transparent;color:#bdcce0;border-radius:14px;display:grid;place-items:center;gap:2px}.ucos-rail-btn{width:52px;min-height:52px;font-size:19px}.ucos-rail-btn small{font-size:9px;color:#869db4}.ucos-rail-btn:hover,.ucos-rail-btn.active{background:#ffffff0c;border-color:#ffffff16;color:white}.ucos-rail-btn.active{box-shadow:inset 3px 0 var(--ucos-accent)}
.ucos-desktop{position:absolute;left:72px;right:0;top:48px;bottom:64px;overflow:auto;padding:22px;z-index:10}.ucos-home{max-width:1280px;margin:0 auto;display:grid;gap:16px}.ucos-home-head{display:flex;align-items:flex-end;justify-content:space-between;gap:14px}.ucos-home-head h1{font-size:28px;letter-spacing:-.6px;margin:0}.ucos-home-head p{margin:5px 0 0;color:var(--ucos-muted);font-size:13px}.ucos-status-pills{display:flex;gap:7px;flex-wrap:wrap}.ucos-pill{border:1px solid #33506c;background:#0a1725b8;border-radius:999px;padding:5px 9px;font-size:10px;color:#b4c6d8}.ucos-pill.good{color:#aaf1c8;border-color:#32664b;background:#0e291d}.ucos-pill.warn{color:#f1db9a;border-color:#67562d;background:#2a220f}
.ucos-command-card{border:1px solid #31506e;background:linear-gradient(135deg,#0f2238df,#0b1929df);border-radius:22px;padding:18px;box-shadow:0 18px 70px #0005;display:grid;grid-template-columns:1fr auto;gap:12px;align-items:center}.ucos-command-card h2{font-size:17px;margin:0 0 4px}.ucos-command-card p{margin:0;color:var(--ucos-muted);font-size:12px}.ucos-command-open{border:1px solid #4876a4;background:#173c66;border-radius:12px;padding:10px 14px;font-weight:700}
.ucos-home-grid{display:grid;grid-template-columns:1.35fr .8fr;gap:16px}.ucos-card{border:1px solid var(--ucos-line2);background:var(--ucos-panel);backdrop-filter:blur(20px);border-radius:var(--ucos-radius);padding:15px;box-shadow:0 14px 50px #0003}.ucos-card-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:11px}.ucos-card-head h3{margin:0;font-size:13px}.ucos-card-head button{background:transparent;border:0;color:#9ab9d9;font-size:11px}.ucos-app-grid{display:grid;grid-template-columns:repeat(4,minmax(105px,1fr));gap:9px}.ucos-app-tile{border:1px solid #253e58;background:#0a1725;border-radius:14px;padding:12px;text-align:left;min-height:86px;transition:.15s transform,.15s border-color,.15s background}.ucos-app-tile:hover{transform:translateY(-2px);border-color:#4c79a5;background:#102238}.ucos-app-tile .ucos-app-icon{font-size:25px;display:block;margin-bottom:8px}.ucos-app-tile b{font-size:12px;display:block}.ucos-app-tile small{font-size:9px;color:var(--ucos-muted);display:block;margin-top:3px;line-height:1.3}.ucos-metric-grid{display:grid;grid-template-columns:1fr 1fr;gap:8px}.ucos-metric{border:1px solid #243d56;background:#091725;border-radius:13px;padding:10px}.ucos-metric b{font-size:19px;display:block}.ucos-metric span{font-size:9px;color:var(--ucos-muted)}.ucos-node-list{display:grid;gap:7px}.ucos-node-card{display:flex;gap:9px;align-items:center;border:1px solid #233c55;background:#0a1725;border-radius:12px;padding:10px}.ucos-node-symbol{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#132a43}.ucos-node-body{min-width:0;flex:1}.ucos-node-body b{font-size:11px;display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ucos-node-body small{font-size:9px;color:var(--ucos-muted)}
.ucos-dock{position:absolute;left:50%;bottom:10px;transform:translateX(-50%);height:48px;border:1px solid #ffffff18;background:#081522d9;backdrop-filter:blur(25px);box-shadow:0 15px 50px #0007;border-radius:17px;padding:5px;display:flex;align-items:center;gap:4px;z-index:950}.ucos-dock-btn{width:38px;height:38px;font-size:20px;position:relative}.ucos-dock-btn:hover,.ucos-dock-btn.running{background:#ffffff10;border-color:#ffffff16}.ucos-dock-btn.running:after{content:'';position:absolute;bottom:2px;width:4px;height:4px;background:var(--ucos-accent);border-radius:50%}
.ucos-window-layer{position:absolute;inset:48px 0 0 72px;z-index:300;pointer-events:none}.ucos-window{position:absolute;left:8%;top:7%;width:min(900px,84vw);height:min(620px,76vh);min-width:360px;min-height:260px;border:1px solid #42617f;background:#0b1724f5;border-radius:18px;box-shadow:var(--ucos-shadow);overflow:hidden;resize:both;pointer-events:auto;display:flex;flex-direction:column}.ucos-window.maximized{left:8px!important;top:8px!important;width:calc(100% - 16px)!important;height:calc(100% - 80px)!important;resize:none}.ucos-window.minimized{display:none}.ucos-window.active{border-color:#5f91bd;box-shadow:0 25px 90px #000c,0 0 0 1px #67aefc33}.ucos-titlebar{height:42px;min-height:42px;border-bottom:1px solid #20364c;background:#102136;display:flex;align-items:center;gap:9px;padding:0 9px;user-select:none;touch-action:none}.ucos-titlebar-icon{width:26px;height:26px;border-radius:8px;background:#17314e;display:grid;place-items:center}.ucos-titlebar-title{font-size:12px;font-weight:700;flex:1}.ucos-window-actions{display:flex;gap:4px}.ucos-window-actions button{width:28px;height:28px;border:0;background:transparent;border-radius:8px;color:#a9bfd4}.ucos-window-actions button:hover{background:#ffffff10}.ucos-window-actions .close:hover{background:#612a36;color:white}.ucos-window-content{flex:1;min-height:0;overflow:auto;padding:14px;background:linear-gradient(180deg,#0b1826,#08131f)}
.ucos-app-toolbar{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-bottom:12px}.ucos-app-toolbar button,.ucos-app-toolbar select,.ucos-app-toolbar input{border:1px solid #36516d;background:#0d1c2c;border-radius:9px;padding:7px 9px;font-size:11px}.ucos-app-toolbar input{min-width:180px;flex:1}.ucos-section{border:1px solid #21384f;background:#091623;border-radius:13px;padding:12px;margin-bottom:10px}.ucos-section h3{font-size:12px;margin:0 0 8px}.ucos-section p{font-size:10px;color:var(--ucos-muted);margin:5px 0}.ucos-list{display:grid;gap:6px}.ucos-list-row{display:flex;align-items:center;gap:8px;border:1px solid #20374e;background:#0d1c2b;border-radius:10px;padding:9px}.ucos-list-row .grow{min-width:0;flex:1}.ucos-list-row b{font-size:11px;display:block}.ucos-list-row small{font-size:9px;color:var(--ucos-muted);display:block;margin-top:2px}.ucos-list-row button{border:1px solid #35516d;background:#12263b;border-radius:8px;padding:6px 8px;font-size:10px}.ucos-empty{padding:22px;text-align:center;color:var(--ucos-muted);font-size:11px}.ucos-code{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid #1e344a;background:#050d15;border-radius:10px;padding:10px;font-size:10px;max-height:260px;overflow:auto}.ucos-terminal{height:100%;display:flex;flex-direction:column;gap:8px}.ucos-terminal-log{flex:1;min-height:180px;overflow:auto;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11px;white-space:pre-wrap;background:#040a10;border:1px solid #1c3043;border-radius:10px;padding:10px}.ucos-terminal-line{display:flex;align-items:center;gap:6px}.ucos-terminal-line span{color:#60d394;font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.ucos-terminal-line input{flex:1;border:0;outline:0;background:transparent;font-family:ui-monospace,SFMono-Regular,Menlo,monospace;color:white}.ucos-cap-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:7px}.ucos-cap-card{border:1px solid #253f58;background:#0b1927;border-radius:11px;padding:9px}.ucos-cap-card b{font-size:10px;display:block}.ucos-cap-card small{font-size:8px;color:var(--ucos-muted);display:block;margin-top:3px}.ucos-cap-card button{margin-top:7px;border:1px solid #31516f;background:#112941;border-radius:7px;padding:5px 7px;font-size:9px}.ucos-camera{display:grid;place-items:center;height:100%;gap:10px}.ucos-camera video{width:100%;height:min(58vh,480px);object-fit:cover;border-radius:14px;background:#02070c;border:1px solid #233f59}.ucos-camera-controls{display:flex;gap:8px}.ucos-camera-controls button{border:1px solid #3e617f;background:#163553;border-radius:999px;padding:9px 14px}.ucos-camera-controls .capture{width:54px;height:54px;border-radius:50%;background:white;color:#09203a;border:6px solid #8fb8dd;box-shadow:0 0 0 3px #fff3}
.ucos-overlay{position:absolute;inset:48px 0 0 72px;background:#03080daf;backdrop-filter:blur(8px);z-index:1200;display:grid;place-items:start center;padding-top:7vh}.ucos-launcher{width:min(760px,90vw);max-height:76vh;overflow:hidden;border:1px solid #466784;background:#0b1826f4;border-radius:22px;box-shadow:var(--ucos-shadow);display:flex;flex-direction:column}.ucos-launcher-search{padding:13px;border-bottom:1px solid #213a52}.ucos-launcher-search input{width:100%;height:42px;border:1px solid #395975;background:#081522;border-radius:13px;padding:0 13px;outline:0}.ucos-launcher-body{overflow:auto;padding:13px}.ucos-launcher-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.ucos-launcher-item{border:1px solid #243d55;background:#0c1a29;border-radius:13px;padding:10px;text-align:center}.ucos-launcher-item:hover{background:#10243a;border-color:#4b7196}.ucos-launcher-item .ucos-app-icon{display:block;font-size:25px;margin-bottom:5px}.ucos-launcher-item span:last-child{font-size:10px}.ucos-launcher-section-title{font-size:9px;text-transform:uppercase;letter-spacing:.12em;color:#7f99b2;margin:5px 2px 8px}
.ucos-flyout{position:absolute;right:10px;top:54px;width:min(360px,92vw);max-height:70vh;overflow:auto;border:1px solid #405f7b;background:#0a1725f2;backdrop-filter:blur(24px);border-radius:17px;box-shadow:var(--ucos-shadow);z-index:1250;padding:12px}.ucos-flyout h3{font-size:12px;margin:0 0 9px}.ucos-quick-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.ucos-quick-btn{border:1px solid #29465f;background:#0d1f31;border-radius:11px;padding:10px;text-align:left}.ucos-quick-btn.active{border-color:#3e7d65;background:#103225}.ucos-quick-btn b{font-size:10px;display:block}.ucos-quick-btn small{font-size:8px;color:var(--ucos-muted)}.ucos-notice{border-bottom:1px solid #1f3448;padding:9px 2px}.ucos-notice:last-child{border:0}.ucos-notice b{font-size:10px}.ucos-notice p{font-size:9px;color:var(--ucos-muted);margin:3px 0}
.ucos-boot{position:absolute;inset:0;z-index:5000;background:#050b12;display:grid;place-items:center;transition:.28s opacity}.ucos-boot.done{opacity:0;pointer-events:none}.ucos-boot-inner{text-align:center}.ucos-boot-logo{width:64px;height:64px;margin:0 auto 15px;border-radius:19px;display:grid;place-items:center;font-size:27px;font-weight:900;background:linear-gradient(135deg,#347fe0,#6bc5ff);box-shadow:0 0 0 1px #ffffff2b,0 20px 70px #1c75d05c}.ucos-boot strong{font-size:16px}.ucos-boot small{display:block;color:#7891a9;font-size:10px;margin-top:5px}.ucos-boot-bar{width:180px;height:3px;background:#172b3f;border-radius:999px;margin:18px auto 0;overflow:hidden}.ucos-boot-bar:after{content:'';display:block;height:100%;width:50%;background:#67adff;border-radius:inherit;animation:ucosboot 1s ease-in-out infinite}@keyframes ucosboot{0%{transform:translateX(-120%)}100%{transform:translateX(240%)}}
#ucosReturnToOS{position:fixed;right:16px;bottom:16px;z-index:999999;border:1px solid #4d7090;background:#0b1b2bdc;backdrop-filter:blur(18px);color:white;border-radius:13px;padding:10px 13px;box-shadow:0 14px 50px #0008;font:600 12px system-ui;display:none}body.ucos-lab-mode #ucosReturnToOS{display:block}
@media(max-width:900px){.ucos-topbar{grid-template-columns:1fr auto}.ucos-global-search{display:none}.ucos-home-grid{grid-template-columns:1fr}.ucos-app-grid{grid-template-columns:repeat(3,1fr)}.ucos-rail{width:60px}.ucos-desktop{left:60px}.ucos-window-layer,.ucos-overlay{left:60px}.ucos-window{width:calc(100vw - 90px);height:76vh;left:12px!important}.ucos-launcher-grid{grid-template-columns:repeat(3,1fr)}}
@media(max-width:620px){.ucos-topbar{height:46px;padding:0 8px}.ucos-brand small{display:none}.ucos-tray-btn .label{display:none}.ucos-rail{display:none}.ucos-desktop{left:0;top:46px;bottom:62px;padding:13px}.ucos-window-layer{left:0;top:46px;bottom:58px}.ucos-window{inset:0!important;width:100%!important;height:100%!important;min-width:0;min-height:0;border-radius:0;resize:none;border-left:0;border-right:0}.ucos-window.maximized{inset:0!important;width:100%!important;height:100%!important}.ucos-window-content{padding:11px}.ucos-overlay{left:0;top:46px;padding:0;place-items:end center}.ucos-launcher{width:100%;max-height:78vh;border-radius:22px 22px 0 0}.ucos-launcher-grid{grid-template-columns:repeat(4,1fr)}.ucos-dock{bottom:7px;height:48px}.ucos-home-head h1{font-size:22px}.ucos-status-pills{display:none}.ucos-command-card{grid-template-columns:1fr}.ucos-app-grid{grid-template-columns:repeat(2,1fr)}.ucos-home-grid{gap:11px}.ucos-card{padding:12px}.ucos-flyout{top:50px;right:6px;width:calc(100vw - 12px)}.ucos-camera video{height:52vh}}
`;
document.head.appendChild(style);

const os=document.createElement('div');
os.id='ucosOS';
os.innerHTML=`
<div class="ucos-wallpaper"></div>
<div class="ucos-topbar">
 <div class="ucos-brand"><div class="ucos-mark">U</div><div><strong>Super API UCOS</strong><small>Universal Capability OS</small></div></div>
 <button class="ucos-global-search" id="ucosGlobalSearch"><span>Search apps, files, devices and capabilities…</span><kbd>Ctrl Space</kbd></button>
 <div class="ucos-tray"><button class="ucos-tray-btn" id="ucosPeerTray"><span class="ucos-tray-dot" id="ucosPeerDot"></span><span class="label">Peer</span></button><button class="ucos-tray-btn" id="ucosQuickTray">⌁ <span class="label">System</span></button><button class="ucos-tray-btn" id="ucosNoticeTray">●</button><div class="ucos-clock"><b id="ucosClock"></b><span id="ucosDate"></span></div></div>
</div>
<nav class="ucos-rail" id="ucosRail"></nav>
<main class="ucos-desktop" id="ucosDesktop"></main>
<div class="ucos-window-layer" id="ucosWindowLayer"></div>
<div class="ucos-dock" id="ucosDock"></div>
<div class="ucos-overlay hidden" id="ucosLauncherOverlay"><div class="ucos-launcher"><div class="ucos-launcher-search"><input id="ucosLauncherSearch" autocomplete="off" placeholder="Search apps, devices, capabilities and actions…"></div><div class="ucos-launcher-body" id="ucosLauncherBody"></div></div></div>
<div class="ucos-flyout hidden" id="ucosQuickPanel"></div>
<div class="ucos-flyout hidden" id="ucosNoticePanel"></div>
<div class="ucos-boot" id="ucosBoot"><div class="ucos-boot-inner"><div class="ucos-boot-logo">U</div><strong>Super API UCOS</strong><small>Discovering capabilities and restoring workspace</small><div class="ucos-boot-bar"></div></div></div>
`;
document.body.appendChild(os);
const returnBtn=document.createElement('button');returnBtn.id='ucosReturnToOS';returnBtn.textContent='← Return to UCOS';document.body.appendChild(returnBtn);
document.body.classList.add('ucos-os-active');

const $=s=>os.querySelector(s);
function addNotice(title,message,kind='info'){
 const item={id:++state.noticeSeq,title:String(title),message:String(message),kind,time:new Date().toISOString()};notices.unshift(item);if(notices.length>40)notices.length=40;renderNotices();return item;
}
function setActiveApp(id){state.activeApp=id;for(const b of os.querySelectorAll('[data-app]'))b.classList.toggle('active',b.dataset.app===id)}
function registerApp(app){appRegistry.set(app.id,{category:'System',singleton:true,...app});return app}
function appButton(app,cls='ucos-app-tile'){return `<button class="${cls}" data-open-app="${esc(app.id)}">${app.icon?`<span class="ucos-app-icon">${app.icon}</span>`:''}<b>${esc(app.title)}</b>${app.description?`<small>${esc(app.description)}</small>`:''}</button>`}
function wireOpeners(root=os){for(const el of root.querySelectorAll('[data-open-app]'))el.onclick=()=>openApp(el.dataset.openApp)}

function focusWindow(win){state.z++;win.style.zIndex=String(state.z);for(const w of state.windows.values())w.classList.toggle('active',w===win);setActiveApp(win.dataset.appId)}
function makeDraggable(win,titlebar){let drag=null;titlebar.addEventListener('pointerdown',e=>{if(e.target.closest('button')||win.classList.contains('maximized')||matchMedia('(max-width:620px)').matches)return;drag={x:e.clientX,y:e.clientY,left:win.offsetLeft,top:win.offsetTop};titlebar.setPointerCapture?.(e.pointerId);focusWindow(win)});titlebar.addEventListener('pointermove',e=>{if(!drag)return;const layer=$('#ucosWindowLayer');const maxX=Math.max(0,layer.clientWidth-win.offsetWidth),maxY=Math.max(0,layer.clientHeight-win.offsetHeight-10);win.style.left=Math.max(0,Math.min(maxX,drag.left+e.clientX-drag.x))+'px';win.style.top=Math.max(0,Math.min(maxY,drag.top+e.clientY-drag.y))+'px'});titlebar.addEventListener('pointerup',()=>drag=null);titlebar.addEventListener('pointercancel',()=>drag=null)}
function closeWindow(id){const record=state.windows.get(id);if(!record)return;try{record._cleanup?.()}catch{}record.remove();state.windows.delete(id);renderDock();const next=[...state.windows.values()].at(-1);if(next)focusWindow(next);else setActiveApp(null)}
function minimizeWindow(id){const w=state.windows.get(id);if(!w)return;w.classList.add('minimized');renderDock();setActiveApp(null)}
function toggleMaximize(id){const w=state.windows.get(id);if(!w)return;w.classList.toggle('maximized');focusWindow(w)}
function restoreWindow(id){const w=state.windows.get(id);if(!w)return;w.classList.remove('minimized');focusWindow(w)}
function openApp(id,options={}){
 const app=appRegistry.get(id);if(!app){addNotice('App unavailable',`No UCOS app registered as ${id}`,'error');return null}
 if(id==='devlab'){enterLab();return null}
 if(app.singleton!==false&&state.windows.has(id)){restoreWindow(id);return state.windows.get(id)}
 const instanceId=app.singleton===false?`${id}-${Date.now()}`:id;
 const win=document.createElement('section');win.className='ucos-window';win.dataset.appId=id;win.dataset.instanceId=instanceId;win.style.left=`${6+(state.windows.size%5)*3}%`;win.style.top=`${5+(state.windows.size%5)*3}%`;win.innerHTML=`<div class="ucos-titlebar"><div class="ucos-titlebar-icon">${app.icon||'◆'}</div><div class="ucos-titlebar-title">${esc(app.title)}</div><div class="ucos-window-actions"><button data-min title="Minimize">—</button><button data-max title="Maximize">□</button><button class="close" data-close title="Close">×</button></div></div><div class="ucos-window-content"></div>`;
 $('#ucosWindowLayer').appendChild(win);state.windows.set(instanceId,win);win.querySelector('[data-min]').onclick=()=>minimizeWindow(instanceId);win.querySelector('[data-max]').onclick=()=>toggleMaximize(instanceId);win.querySelector('[data-close]').onclick=()=>closeWindow(instanceId);win.addEventListener('pointerdown',()=>focusWindow(win));makeDraggable(win,win.querySelector('.ucos-titlebar'));focusWindow(win);
 const ctx={id:instanceId,app,win,content:win.querySelector('.ucos-window-content'),options,close:()=>closeWindow(instanceId),notice:addNotice,open:openApp,setCleanup:fn=>win._cleanup=fn};
 Promise.resolve(app.render?.(ctx)).catch(e=>{ctx.content.innerHTML=`<div class="ucos-empty">${esc(e?.message||e)}</div>`;addNotice(`${app.title} error`,e?.message||String(e),'error')});
 renderDock();closeLauncher();return win
}

function renderHome(){
 const h=UCOS.health();const apps=['files','devices','camera','capabilities','network','terminal','flows','settings'];
 const nodes=h.nodes||[];const peer=nodes.find(n=>!n.local&&n.online);
 $('#ucosDesktop').innerHTML=`<div class="ucos-home"><div class="ucos-home-head"><div><h1>Universal Capability Workspace</h1><p>Use capabilities through apps. Developer-level APIs stay available when you need them.</p></div><div class="ucos-status-pills"><span class="ucos-pill ${h.secureContext?'good':'warn'}">${h.secureContext?'Secure context':'Limited context'}</span><span class="ucos-pill ${h.peerConnected?'good':''}">${h.peerConnected?'Peer connected':'Local only'}</span><span class="ucos-pill ${h.sessionAuthorized?'good':'warn'}">${h.sessionAuthorized?'Session control on':'Session control off'}</span></div></div><div class="ucos-command-card"><div><h2>What do you want to do?</h2><p>Search apps, devices, capabilities or actions. UCOS resolves the implementation underneath.</p></div><button class="ucos-command-open" id="ucosHomeSearch">Open command center</button></div><div class="ucos-home-grid"><section class="ucos-card"><div class="ucos-card-head"><h3>Apps</h3><button id="ucosAllApps">Open launcher</button></div><div class="ucos-app-grid">${apps.map(id=>appButton(appRegistry.get(id))).join('')}</div></section><section class="ucos-card"><div class="ucos-card-head"><h3>System</h3><button data-open-app="capabilities">Details</button></div><div class="ucos-metric-grid"><div class="ucos-metric"><b>${h.capabilities.total}</b><span>Capabilities</span></div><div class="ucos-metric"><b>${h.providers.length}</b><span>Providers</span></div><div class="ucos-metric"><b>${h.transports.length}</b><span>Transports</span></div><div class="ucos-metric"><b>${h.nodes.length}</b><span>Nodes</span></div></div><div style="height:9px"></div><div class="ucos-node-list">${nodes.slice(0,3).map(n=>`<div class="ucos-node-card"><div class="ucos-node-symbol">${n.local?'💻':'📱'}</div><div class="ucos-node-body"><b>${esc(n.label||n.id)}</b><small>${n.local?'This device':n.online?'Connected node':'Offline node'} • ${(n.capabilities?.length||n.capabilityDetails?.length||0)} capabilities</small></div><span class="ucos-pill ${n.online?'good':''}">${n.online?'Ready':'Offline'}</span></div>`).join('')||'<div class="ucos-empty">No nodes discovered.</div>'}</div>${peer?'':'<p style="font-size:9px;color:var(--ucos-muted);margin:9px 2px 0">Pair another device in Developer Lab to extend this capability fabric.</p>'}</section></div></div>`;
 $('#ucosHomeSearch').onclick=openLauncher;$('#ucosAllApps').onclick=openLauncher;wireOpeners($('#ucosDesktop'));
}

function renderRail(){const ids=['home','files','devices','capabilities','network','devlab'];$('#ucosRail').innerHTML=ids.map(id=>{if(id==='home')return `<button class="ucos-rail-btn active" id="ucosHomeBtn">⌂<small>Home</small></button>`;const a=appRegistry.get(id);return `<button class="ucos-rail-btn" data-app="${id}" data-open-app="${id}">${a.icon}<small>${esc(a.short||a.title)}</small></button>`}).join('')+'<div class="ucos-rail-spacer"></div><button class="ucos-rail-btn" data-app="settings" data-open-app="settings">⚙<small>Settings</small></button>';$('#ucosHomeBtn').onclick=()=>{renderHome();setActiveApp(null)};wireOpeners($('#ucosRail'))}
function renderDock(){const pinned=['launcher','files','devices','camera','terminal'];$('#ucosDock').innerHTML=pinned.map(id=>id==='launcher'?`<button class="ucos-dock-btn" id="ucosLauncherBtn" title="Launcher">◉</button>`:(()=>{const a=appRegistry.get(id),running=[...state.windows.values()].some(w=>w.dataset.appId===id&&!w.classList.contains('minimized'));return `<button class="ucos-dock-btn ${running?'running':''}" data-open-app="${id}" title="${esc(a.title)}">${a.icon}</button>`})()).join('');$('#ucosLauncherBtn').onclick=()=>state.launcher?closeLauncher():openLauncher();wireOpeners($('#ucosDock'))}

function launcherResults(q=''){const needle=q.trim().toLowerCase();const apps=[...appRegistry.values()].filter(a=>a.id!=='home'&&(!needle||`${a.title} ${a.description||''} ${a.category||''} ${(a.keywords||[]).join(' ')}`.toLowerCase().includes(needle)));const caps=needle?UCOS.capabilities.list({query:q}).slice(0,16):[];const nodes=needle?UCOS.health().nodes.filter(n=>`${n.label} ${n.id}`.toLowerCase().includes(needle)).slice(0,8):[];return{apps,caps,nodes}}
function renderLauncher(){const q=$('#ucosLauncherSearch').value||'',r=launcherResults(q);$('#ucosLauncherBody').innerHTML=`<div class="ucos-launcher-section-title">${q?'Apps':'Applications'}</div><div class="ucos-launcher-grid">${r.apps.map(a=>appButton(a,'ucos-launcher-item')).join('')||'<div class="ucos-empty">No apps found</div>'}</div>${r.nodes.length?`<div class="ucos-launcher-section-title" style="margin-top:15px">Devices</div><div class="ucos-list">${r.nodes.map(n=>`<button class="ucos-list-row" data-open-app="devices"><span>${n.local?'💻':'📱'}</span><span class="grow"><b>${esc(n.label||n.id)}</b><small>${n.online?'Ready':'Offline'}</small></span></button>`).join('')}</div>`:''}${r.caps.length?`<div class="ucos-launcher-section-title" style="margin-top:15px">Capabilities</div><div class="ucos-list">${r.caps.map(c=>`<button class="ucos-list-row" data-cap="${esc(c.id)}"><span>⚡</span><span class="grow"><b>${esc(c.label)}</b><small>${esc(c.domain)} • ${esc(c.id)}</small></span></button>`).join('')}</div>`:''}`;wireOpeners($('#ucosLauncherBody'));for(const el of $('#ucosLauncherBody').querySelectorAll('[data-cap]'))el.onclick=()=>openApp('capabilities',{query:el.dataset.cap})}
function openLauncher(){state.launcher=true;$('#ucosLauncherOverlay').classList.remove('hidden');$('#ucosLauncherSearch').value='';renderLauncher();setTimeout(()=>$('#ucosLauncherSearch').focus(),0)}function closeLauncher(){state.launcher=false;$('#ucosLauncherOverlay').classList.add('hidden')}

function renderQuick(){const h=UCOS.health();$('#ucosQuickPanel').innerHTML=`<h3>Quick settings</h3><div class="ucos-quick-grid"><button class="ucos-quick-btn ${h.peerConnected?'active':''}" id="qPeer"><b>${h.peerConnected?'Peer connected':'Peer offline'}</b><small>Open Devices</small></button><button class="ucos-quick-btn ${h.sessionAuthorized?'active':''}" id="qSession"><b>Session control</b><small>${h.sessionAuthorized?'Authorized':'Off'}</small></button><button class="ucos-quick-btn ${navigator.onLine?'active':''}" id="qNetwork"><b>${navigator.onLine?'Online':'Offline'}</b><small>Network Center</small></button><button class="ucos-quick-btn ${h.secureContext?'active':''}" id="qSecure"><b>Secure context</b><small>${h.secureContext?'Available':'Unavailable'}</small></button></div><div class="ucos-section" style="margin-top:10px;margin-bottom:0"><h3>Capability fabric</h3><p>${h.capabilities.total} capabilities • ${h.providers.length} providers • ${h.nodes.length} nodes</p><div class="ucos-app-toolbar" style="margin:8px 0 0"><button id="qRefresh">Refresh</button><button id="qAdvertise">Advertise</button></div></div>`;$('#qPeer').onclick=()=>{toggleQuick(false);openApp('devices')};$('#qNetwork').onclick=()=>{toggleQuick(false);openApp('network')};$('#qSession').onclick=()=>{const c=query('#allowRequests');if(!c){addNotice('Session control','Developer Lab session control is unavailable.');return}c.checked=!c.checked;c.dispatchEvent(new Event('change',{bubbles:true}));UCOS.refresh();renderQuick();updateTray();renderHome()};$('#qRefresh').onclick=()=>{UCOS.refresh();renderQuick();renderHome();addNotice('Capability fabric','Registry refreshed.')};$('#qAdvertise').onclick=()=>addNotice('Capability advertisement',UCOS.sendAdvertisement()?'Sent to paired peer.':'No open peer channel.')}
function toggleQuick(force){state.quick=force??!state.quick;$('#ucosQuickPanel').classList.toggle('hidden',!state.quick);if(state.quick){state.notifications=false;$('#ucosNoticePanel').classList.add('hidden');renderQuick()}}
function renderNotices(){if(!os)return;$('#ucosNoticePanel').innerHTML=`<div class="ucos-card-head"><h3>Notifications</h3><button id="ucosClearNotices">Clear</button></div>${notices.length?notices.map(n=>`<div class="ucos-notice"><b>${esc(n.title)}</b><p>${esc(n.message)}</p></div>`).join(''):'<div class="ucos-empty">No notifications</div>'}`;$('#ucosClearNotices').onclick=()=>{notices.length=0;renderNotices()}}
function toggleNotices(){state.notifications=!state.notifications;$('#ucosNoticePanel').classList.toggle('hidden',!state.notifications);if(state.notifications){state.quick=false;$('#ucosQuickPanel').classList.add('hidden');renderNotices()}}
function updateTray(){const h=UCOS.health();$('#ucosPeerDot').classList.toggle('live',h.peerConnected);$('#ucosPeerTray').title=h.peerConnected?'Paired peer connected':'No paired peer';}
function updateClock(){$('#ucosClock').textContent=nowTime();$('#ucosDate').textContent=nowDate()}

function enterLab(){state.lab=true;document.body.classList.remove('ucos-os-active');document.body.classList.add('ucos-lab-mode');os.style.display='none';returnBtn.style.display='block';window.scrollTo({top:0,behavior:'instant'});addNotice('Developer Lab','Legacy Super API Lab opened.')}
function leaveLab(){state.lab=false;document.body.classList.remove('ucos-lab-mode');document.body.classList.add('ucos-os-active');os.style.display='block';returnBtn.style.display='none';UCOS.refresh();renderHome();updateTray()}
returnBtn.onclick=leaveLab;

registerApp({id:'files',title:'Files',short:'Files',icon:'📁',description:'Local files, folders and UCOS storage',keywords:['storage','opfs','folder','file'],render:async ctx=>{
 ctx.content.innerHTML=`<div class="ucos-app-toolbar"><button id="filePick">Open file</button><button id="folderPick">Open folder</button><button id="storageHealth">Storage health</button><button id="storageRefresh">Refresh</button></div><div class="ucos-section"><h3>UCOS storage</h3><p>Browser-private storage uses OPFS/IndexedDB with fallbacks. User-selected files and directories remain browser permission controlled.</p><div id="fileStorage" class="ucos-list"></div></div><div class="ucos-section"><h3>Mounted selection</h3><div id="fileMount" class="ucos-empty">No file or folder selected in this window.</div></div>`;
 const mount=ctx.content.querySelector('#fileMount'),list=ctx.content.querySelector('#fileStorage');
 const refresh=async()=>{const health=globalThis.SuperApiUCOSStorage?.health?.()||{};let keys=[];try{keys=await globalThis.SuperApiUCOSStorage?.list?.('workspace')||[]}catch{}list.innerHTML=`<div class="ucos-list-row"><span>💽</span><span class="grow"><b>UCOS private storage</b><small>${Object.entries(health).filter(([,v])=>v).map(([k])=>k).join(' • ')||'memory fallback'}</small></span></div>${keys.map(k=>`<div class="ucos-list-row"><span>📄</span><span class="grow"><b>${esc(k)}</b><small>workspace namespace</small></span></div>`).join('')}`};
 ctx.content.querySelector('#filePick').onclick=async()=>{try{if(globalThis.showOpenFilePicker){const[h]=await showOpenFilePicker();const f=await h.getFile();mount.className='ucos-list';mount.innerHTML=`<div class="ucos-list-row"><span>📄</span><span class="grow"><b>${esc(f.name)}</b><small>${f.type||'file'} • ${f.size.toLocaleString()} bytes</small></span></div>`}else{const input=document.createElement('input');input.type='file';input.onchange=()=>{const f=input.files?.[0];if(f){mount.className='ucos-list';mount.innerHTML=`<div class="ucos-list-row"><span>📄</span><span class="grow"><b>${esc(f.name)}</b><small>${f.type||'file'} • ${f.size.toLocaleString()} bytes</small></span></div>`}};input.click()}}catch(e){ctx.notice('Files',e.message,'error')}};
 ctx.content.querySelector('#folderPick').onclick=async()=>{try{if(!globalThis.showDirectoryPicker)throw new Error('Directory picker is not available in this browser.');const h=await showDirectoryPicker();const names=[];for await(const [name,entry] of h.entries()){names.push({name,kind:entry.kind});if(names.length>=100)break}mount.className='ucos-list';mount.innerHTML=`<div class="ucos-list-row"><span>📂</span><span class="grow"><b>${esc(h.name)}</b><small>${names.length} entries shown</small></span></div>`+names.map(x=>`<div class="ucos-list-row"><span>${x.kind==='directory'?'📁':'📄'}</span><span class="grow"><b>${esc(x.name)}</b><small>${x.kind}</small></span></div>`).join('')}catch(e){ctx.notice('Files',e.message,'error')}};
 ctx.content.querySelector('#storageHealth').onclick=()=>{mount.className='ucos-code';mount.textContent=safe(globalThis.SuperApiUCOSStorage?.health?.()||{})};ctx.content.querySelector('#storageRefresh').onclick=refresh;await refresh()
}});

registerApp({id:'devices',title:'Devices',short:'Devices',icon:'📱',description:'Capability nodes and connected peers',keywords:['peer','phone','node','device'],render:ctx=>{const draw=()=>{const h=UCOS.health(),nodes=h.nodes||[];ctx.content.innerHTML=`<div class="ucos-app-toolbar"><button id="devRefresh">Refresh</button><button id="devAdvertise">Advertise capabilities</button><button id="devPing" ${h.peerConnected?'':'disabled'}>Ping peer</button><button id="devPair">Open pairing tools</button></div><div class="ucos-section"><h3>Capability nodes</h3><div class="ucos-list">${nodes.map(n=>`<div class="ucos-list-row"><span style="font-size:22px">${n.local?'💻':'📱'}</span><span class="grow"><b>${esc(n.label||n.id)}</b><small>${n.local?'Local browser node':n.transportId||'remote'} • ${(n.capabilities?.length||n.capabilityDetails?.length||0)} capabilities • ${n.online?'ready':'offline'}</small></span><button data-node="${esc(n.id)}">Inspect</button></div>`).join('')||'<div class="ucos-empty">No nodes available.</div>'}</div></div><div class="ucos-section"><h3>Fabric status</h3><pre class="ucos-code">${esc(safe({peerConnected:h.peerConnected,sessionAuthorized:h.sessionAuthorized,transports:h.transports}))}</pre></div>`;ctx.content.querySelector('#devRefresh').onclick=()=>{UCOS.refresh();draw()};ctx.content.querySelector('#devAdvertise').onclick=()=>ctx.notice('Devices',UCOS.sendAdvertisement()?'Capability advertisement sent.':'No paired peer channel.');ctx.content.querySelector('#devPing').onclick=async()=>{try{ctx.notice('Peer response',safe(await UCOS.ping()))}catch(e){ctx.notice('Peer ping failed',e.message,'error')}};ctx.content.querySelector('#devPair').onclick=()=>enterLab();for(const b of ctx.content.querySelectorAll('[data-node]'))b.onclick=()=>{const n=UCOS.nodes.get(b.dataset.node);ctx.content.querySelector('pre').textContent=safe(n)}};draw();const on=()=>draw();UCOS.events.addEventListener('nodes',on);ctx.setCleanup(()=>UCOS.events.removeEventListener('nodes',on))}});

registerApp({id:'network',title:'Network Center',short:'Network',icon:'🌐',description:'Connectivity, transports and peer routes',keywords:['webrtc','internet','transport','connection'],render:ctx=>{const draw=()=>{const h=UCOS.health(),c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;ctx.content.innerHTML=`<div class="ucos-app-toolbar"><button id="netRefresh">Refresh</button><button id="netLab">Advanced network lab</button></div><div class="ucos-section"><h3>Connectivity</h3><div class="ucos-metric-grid"><div class="ucos-metric"><b>${navigator.onLine?'Online':'Offline'}</b><span>Browser network state</span></div><div class="ucos-metric"><b>${c?.effectiveType||'—'}</b><span>Effective type</span></div><div class="ucos-metric"><b>${c?.rtt??'—'}</b><span>RTT ms</span></div><div class="ucos-metric"><b>${c?.downlink??'—'}</b><span>Downlink Mbps</span></div></div></div><div class="ucos-section"><h3>Transports</h3><div class="ucos-list">${h.transports.map(t=>`<div class="ucos-list-row"><span>${t.available?'●':'○'}</span><span class="grow"><b>${esc(t.label||t.id)}</b><small>${esc(t.kind)} • ${t.available?'available':'unavailable'}</small></span></div>`).join('')}</div></div><div class="ucos-section"><h3>Peer route</h3><p>${h.peerConnected?'A WebRTC-compatible paired-peer transport is available.':'No paired peer is currently connected.'}</p></div>`;ctx.content.querySelector('#netRefresh').onclick=()=>{UCOS.refresh();draw()};ctx.content.querySelector('#netLab').onclick=enterLab};draw()}});

registerApp({id:'capabilities',title:'Capability Center',short:'APIs',icon:'⚡',description:'Discover and use browser capabilities',keywords:['api','capability','provider','execute'],render:ctx=>{ctx.content.innerHTML=`<div class="ucos-app-toolbar"><input id="capSearch" placeholder="Search capability…"><select id="capDomain"><option value="">All domains</option></select><button id="capRefresh">Refresh</button></div><div id="capSummary" class="ucos-section"></div><div id="capGrid" class="ucos-cap-grid"></div><div class="ucos-section"><h3>Advanced executor</h3><p>This is optional developer-level access. Normal UCOS apps resolve capabilities automatically.</p><div class="ucos-app-toolbar"><select id="capExec"></select><select id="capMode"><option value="auto">Auto</option><option value="local">Local</option><option value="peer">Peer</option></select><select id="capOp"><option>execute</option><option>test</option><option>inspect</option><option>read</option><option>write</option><option>connect</option><option>stream</option></select><button id="capRun">Run</button></div><textarea id="capArgs" class="ucos-code" style="width:100%;min-height:70px">{}</textarea><pre id="capOut" class="ucos-code">Select a capability.</pre></div>`;
 const search=ctx.content.querySelector('#capSearch'),domain=ctx.content.querySelector('#capDomain'),grid=ctx.content.querySelector('#capGrid'),exec=ctx.content.querySelector('#capExec'),summary=ctx.content.querySelector('#capSummary');
 const draw=()=>{UCOS.refresh();const all=UCOS.capabilities.list(),domains=[...new Set(all.map(c=>c.domain))].sort();const prev=domain.value;domain.innerHTML='<option value="">All domains</option>'+domains.map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');if(domains.includes(prev))domain.value=prev;const q=search.value.trim().toLowerCase(),rows=all.filter(c=>(!domain.value||c.domain===domain.value)&&(!q||`${c.label} ${c.id} ${c.domain}`.toLowerCase().includes(q))).slice(0,300);const h=UCOS.health();summary.innerHTML=`<div class="ucos-metric-grid"><div class="ucos-metric"><b>${h.capabilities.total}</b><span>Total capabilities</span></div><div class="ucos-metric"><b>${h.providers.length}</b><span>Providers</span></div><div class="ucos-metric"><b>${h.nodes.length}</b><span>Nodes</span></div><div class="ucos-metric"><b>${rows.length}</b><span>Shown</span></div></div>`;grid.innerHTML=rows.map(c=>`<div class="ucos-cap-card"><b>${esc(c.label)}</b><small>${esc(c.domain)} • ${esc(c.id)}</small><small>${esc((c.operations||[]).join(', ')||'execute')}</small><button data-use="${esc(c.id)}">Use</button></div>`).join('')||'<div class="ucos-empty">No capabilities match.</div>';exec.innerHTML=rows.map(c=>`<option value="${esc(c.id)}">${esc(c.label)}</option>`).join('');for(const b of grid.querySelectorAll('[data-use]'))b.onclick=()=>{exec.value=b.dataset.use;ctx.content.querySelector('#capOut').textContent=safe(UCOS.capabilities.get(b.dataset.use));ctx.content.querySelector('#capOut').scrollIntoView({behavior:'smooth',block:'nearest'})}};
 search.oninput=draw;domain.onchange=draw;ctx.content.querySelector('#capRefresh').onclick=draw;ctx.content.querySelector('#capRun').onclick=async()=>{const out=ctx.content.querySelector('#capOut');try{const args=JSON.parse(ctx.content.querySelector('#capArgs').value||'{}');out.textContent='Executing…';out.textContent=safe(await UCOS.execute({capabilityId:exec.value,operation:ctx.content.querySelector('#capOp').value,args,mode:ctx.content.querySelector('#capMode').value}))}catch(e){out.textContent=e.envelope?safe(e.envelope):`${e.name}: ${e.message}`}};if(ctx.options.query)search.value=ctx.options.query;draw()
}});

registerApp({id:'terminal',title:'Terminal',short:'Terminal',icon:'>_',description:'UCOS command shell',keywords:['command','cli','console'],render:ctx=>{ctx.content.innerHTML=`<div class="ucos-terminal"><div class="ucos-terminal-log" id="termLog">Super API UCOS shell\nType 'help' for commands.\n</div><div class="ucos-terminal-line"><span>ucos $</span><input id="termInput" autocomplete="off" spellcheck="false"></div></div>`;const log=ctx.content.querySelector('#termLog'),input=ctx.content.querySelector('#termInput');const print=v=>{log.textContent+=`${typeof v==='string'?v:safe(v)}\n`;log.scrollTop=log.scrollHeight};const run=async raw=>{const [cmd,...args]=raw.trim().split(/\s+/);if(!cmd)return;print(`$ ${raw}`);try{switch(cmd.toLowerCase()){case'help':print('help | health | caps [query] | nodes | providers | transports | route <capability> | open <app> | apps | clear | lab');break;case'health':print(UCOS.health());break;case'caps':print(UCOS.capabilities.list({query:args.join(' ')}).slice(0,100).map(c=>({id:c.id,label:c.label,domain:c.domain})));break;case'nodes':print(UCOS.nodes.export());break;case'providers':print(UCOS.providers.list().map(p=>({id:p.id,label:p.label,priority:p.priority})));break;case'transports':print(UCOS.transports.list().map(t=>({id:t.id,label:t.label,kind:t.kind,available:!!t.available?.()})));break;case'route':print(UCOS.route(args.join(' ')));break;case'open':openApp(args[0]);break;case'apps':print([...appRegistry.keys()]);break;case'clear':log.textContent='';break;case'lab':enterLab();break;default:print(`Unknown command: ${cmd}`)}}catch(e){print(`${e.name}: ${e.message}`)}};input.onkeydown=e=>{if(e.key==='Enter'){const v=input.value;input.value='';run(v)}};setTimeout(()=>input.focus(),0)}});

registerApp({id:'camera',title:'Camera',short:'Camera',icon:'📷',description:'Local browser camera',keywords:['photo','video','media'],render:async ctx=>{ctx.content.innerHTML=`<div class="ucos-camera"><video id="camView" autoplay playsinline muted></video><div class="ucos-camera-controls"><button id="camFlip">Flip</button><button class="capture" id="camCapture" title="Capture"></button><button id="camStop">Stop</button></div><div id="camResult"></div></div>`;let stream=null,facing='environment';const video=ctx.content.querySelector('#camView'),result=ctx.content.querySelector('#camResult');const start=async()=>{try{stream?.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facing}},audio:false});video.srcObject=stream;await video.play().catch(()=>{})}catch(e){result.innerHTML=`<div class="ucos-empty">${esc(e.message)}</div>`}};ctx.content.querySelector('#camFlip').onclick=()=>{facing=facing==='environment'?'user':'environment';start()};ctx.content.querySelector('#camStop').onclick=()=>{stream?.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null};ctx.content.querySelector('#camCapture').onclick=()=>{if(!video.videoWidth)return;const c=document.createElement('canvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);c.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`ucos-photo-${Date.now()}.jpg`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);ctx.notice('Camera','Photo captured and download requested.')},'image/jpeg',.82)};ctx.setCleanup(()=>stream?.getTracks().forEach(t=>t.stop()));await start()}});

registerApp({id:'flows',title:'Flows',short:'Flows',icon:'⤳',description:'Compose capability actions into workflows',keywords:['automation','pipeline','workflow'],render:ctx=>{const flows=[{id:'health',title:'System Health',desc:'Refresh fabric and collect health snapshot',run:async()=>{UCOS.refresh();return UCOS.health()}},{id:'peer',title:'Peer Handshake',desc:'Advertise capabilities and ping the connected peer',run:async()=>({advertised:UCOS.sendAdvertisement(),ping:await UCOS.ping()})},{id:'storage',title:'Storage Check',desc:'Inspect available UCOS storage adapters',run:async()=>globalThis.SuperApiUCOSStorage?.health?.()||{}},{id:'network',title:'Network Snapshot',desc:'Collect online state and connection hints',run:async()=>{const c=navigator.connection||{};return{online:navigator.onLine,effectiveType:c.effectiveType,rtt:c.rtt,downlink:c.downlink,peerConnected:UCOS.health().peerConnected}}}];ctx.content.innerHTML=`<div class="ucos-section"><h3>Capability flows</h3><p>These are composable OS-level workflows. They use the UCOS fabric instead of exposing raw API panels.</p><div class="ucos-list">${flows.map(f=>`<div class="ucos-list-row"><span>⤳</span><span class="grow"><b>${esc(f.title)}</b><small>${esc(f.desc)}</small></span><button data-flow="${f.id}">Run</button></div>`).join('')}</div></div><pre id="flowOut" class="ucos-code">Choose a flow.</pre>`;for(const b of ctx.content.querySelectorAll('[data-flow]'))b.onclick=async()=>{const out=ctx.content.querySelector('#flowOut'),f=flows.find(x=>x.id===b.dataset.flow);try{out.textContent='Running…';out.textContent=safe(await f.run());ctx.notice('Flow completed',f.title)}catch(e){out.textContent=`${e.name}: ${e.message}`;ctx.notice('Flow failed',e.message,'error')}}}});

registerApp({id:'settings',title:'Settings',short:'Settings',icon:'⚙',description:'UCOS system and capability preferences',keywords:['preferences','install','pwa','session'],render:ctx=>{const h=UCOS.health();ctx.content.innerHTML=`<div class="ucos-section"><h3>System</h3><div class="ucos-list"><div class="ucos-list-row"><span>🔒</span><span class="grow"><b>Secure context</b><small>${h.secureContext?'Available':'Unavailable'}</small></span></div><div class="ucos-list-row"><span>🧩</span><span class="grow"><b>Capability fabric</b><small>${h.capabilities.total} capabilities • ${h.providers.length} providers</small></span><button id="settingsRefresh">Refresh</button></div><div class="ucos-list-row"><span>📱</span><span class="grow"><b>Install UCOS</b><small>Install as a standalone PWA when your browser offers installation.</small></span><button id="settingsInstall" ${state.installPrompt?'':'disabled'}>Install</button></div></div></div><div class="ucos-section"><h3>Peer session</h3><p>App-level session authorization never replaces browser or operating-system permission prompts.</p><div class="ucos-list-row"><span>🔗</span><span class="grow"><b>Session control</b><small>${h.sessionAuthorized?'Authorized':'Off'}</small></span><button id="settingsSession">${h.sessionAuthorized?'Turn off':'Turn on'}</button></div></div><div class="ucos-section"><h3>Developer access</h3><div class="ucos-list-row"><span>🛠</span><span class="grow"><b>Super API Lab</b><small>Raw API catalog, peer pairing, diagnostics, scanners and protocol tools.</small></span><button id="settingsLab">Open Lab</button></div></div>`;ctx.content.querySelector('#settingsRefresh').onclick=()=>{UCOS.refresh();ctx.close();openApp('settings')};ctx.content.querySelector('#settingsInstall').onclick=async()=>{if(!state.installPrompt)return;await state.installPrompt.prompt();state.installPrompt=null};ctx.content.querySelector('#settingsSession').onclick=()=>{const c=query('#allowRequests');if(c){c.checked=!c.checked;c.dispatchEvent(new Event('change',{bubbles:true}));UCOS.refresh();ctx.close();openApp('settings')}};ctx.content.querySelector('#settingsLab').onclick=enterLab}});

registerApp({id:'devlab',title:'Developer Lab',short:'Dev',icon:'🛠',description:'Full legacy Super API explorer and diagnostics',keywords:['developer','api lab','peer','scanner'],render:()=>{}});
registerApp({id:'about',title:'About UCOS',icon:'ⓘ',description:'Architecture and runtime information',render:ctx=>{const h=UCOS.health();ctx.content.innerHTML=`<div class="ucos-section"><h3>Super API UCOS</h3><p>A browser-native Universal Capability OS built above the browser security/runtime layer. It discovers, normalizes, routes and composes local and peer capabilities without pretending browser protections can be bypassed.</p></div><pre class="ucos-code">${esc(safe(h))}</pre>`}});

function init(){renderRail();renderDock();renderHome();renderNotices();updateTray();updateClock();setInterval(updateClock,30000);$('#ucosGlobalSearch').onclick=openLauncher;$('#ucosLauncherSearch').oninput=renderLauncher;$('#ucosLauncherOverlay').addEventListener('pointerdown',e=>{if(e.target===$('#ucosLauncherOverlay'))closeLauncher()});$('#ucosQuickTray').onclick=()=>toggleQuick();$('#ucosPeerTray').onclick=()=>openApp('devices');$('#ucosNoticeTray').onclick=toggleNotices;document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.code==='Space'){e.preventDefault();state.launcher?closeLauncher():openLauncher()}else if(e.key==='Escape'){if(state.launcher)closeLauncher();if(state.quick)toggleQuick(false);if(state.notifications){state.notifications=false;$('#ucosNoticePanel').classList.add('hidden')}}});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;addNotice('Install available','UCOS can be installed as a standalone web app.')});window.addEventListener('online',()=>{UCOS.refresh();updateTray();renderHome();addNotice('Network','Back online.')});window.addEventListener('offline',()=>{UCOS.refresh();updateTray();renderHome();addNotice('Network','Browser reports offline.','warn')});UCOS.events.addEventListener('nodes',()=>{updateTray();renderHome()});UCOS.events.addEventListener('capabilities',()=>renderHome());UCOS.events.addEventListener('telemetry',e=>{const d=e.detail||{};if(d.status==='error')addNotice('Capability execution failed',d.error||d.capabilityId||'Unknown error','error')});setTimeout(()=>{$('#ucosBoot').classList.add('done');setTimeout(()=>$('#ucosBoot')?.remove(),350);state.booted=true},480);addNotice('UCOS ready',`${UCOS.health().capabilities.total} capabilities discovered on this node.`)}
init();
})();
