(()=>{
'use strict';
if(globalThis.SuperApiUCOSRuntime)return;
const moduleBase=new URL('../',document.currentScript?.src||location.href);
const Core=globalThis.SuperApiUCOSRuntimeCore,UCOS=globalThis.SuperApiUCOS,Storage=globalThis.SuperApiUCOSStorage,Security=globalThis.SuperApiUCOSSecurity;
if(!Core||!UCOS){console.error('UCOS runtime requires runtime core and fabric');return}
const manifests=Core.createManifestRegistry(),resources=Core.createResourceManager(),processes=Core.createProcessManager(resources),events=Core.createEventBus();
const processPorts=new Map();
const grantAdapter={async get(k){return Storage?.get?.('runtime-grants',k,{preferred:['indexeddb','local','memory']})??null},async set(k,v){return Storage?.set?.('runtime-grants',k,v,{preferred:['indexeddb','local','memory']})},async delete(k){return Storage?.delete?.('runtime-grants',k,{preferred:['indexeddb','local','memory']})},async entries(){const keys=await Storage?.list?.('runtime-grants',{preferred:['indexeddb','local','memory']})||[];return Promise.all(keys.map(async k=>[k,await this.get(k)]))}};
const grants=Core.createGrantStore(grantAdapter),pendingPrompts=new Map();
function audit(type,data={},severity='info'){try{return Security?.auditEvent?.(type,data,severity)}catch{return null}}
async function promptGrant(req){const id=Core.id('grant'),ipcRequestId=String(req.meta?.ipcRequestId||'');events.emit('permission-request',{id,...req});audit('permission-prompt',{appId:req.appId,capabilityId:req.capabilityId,operation:req.operation,ipcRequestId:ipcRequestId||null});return new Promise(resolve=>{const timer=setTimeout(()=>{pendingPrompts.delete(id);audit('permission-timeout',{appId:req.appId,capabilityId:req.capabilityId,ipcRequestId:ipcRequestId||null},'warn');resolve({state:'denied',scope:'session',reason:'prompt-timeout'})},30000);pendingPrompts.set(id,{appId:req.appId,pid:String(req.meta?.pid||''),ipcRequestId,resolve:v=>{clearTimeout(timer);resolve(v)}})})}
function resolvePermission(id,decision){const p=pendingPrompts.get(id);if(!p)return false;pendingPrompts.delete(id);p.resolve(decision);audit('permission-decision',{requestId:id,state:decision?.state,scope:decision?.scope,reason:decision?.reason},decision?.state==='granted'?'info':'warn');return true}
function cancelPromptsForApp(appId,reason='app-stopped',pid=''){let count=0;for(const[id,p]of pendingPrompts){if(p.appId!==appId||pid&&p.pid!==pid)continue;pendingPrompts.delete(id);p.resolve({state:'denied',scope:'session',reason});count++}if(count)audit('permission-prompts-cancelled',{appId,pid:pid||null,count,reason},'info');return count}
function cancelPromptForRequest(appId,pid,ipcRequestId,reason='ipc-cancelled'){if(!ipcRequestId)return 0;let count=0;for(const[id,p]of pendingPrompts){if(p.appId!==appId||p.pid!==pid||p.ipcRequestId!==ipcRequestId)continue;pendingPrompts.delete(id);p.resolve({state:'denied',scope:'session',reason});count++}if(count)audit('permission-request-cancelled',{appId,pid,ipcRequestId,count,reason},'info');return count}
const broker=Core.createCapabilityBroker({
 manifests,grants,prompt:promptGrant,execute:cmd=>UCOS.execute(cmd),
 authorize:ctx=>Security?.authorize?.({appId:ctx.appId,capabilityId:ctx.capabilityId,operation:ctx.operation,nodeId:ctx.targetNodeId||'*',ttlMs:30000,uses:1})||null,
 finalize:({auth,appId,capabilityId,operation,targetNodeId})=>{if(auth?.id)Security?.consumeToken?.(auth.id,{appId,capabilityId,operation,nodeId:targetNodeId||'*'})},
 audit
});
const installedKey='installed-manifests';
async function persistInstalled(){if(Storage)await Storage.set('runtime',installedKey,manifests.export().filter(m=>!m.system),{preferred:['indexeddb','local','memory']})}
async function restoreInstalled(){try{if(globalThis.__UCOS_SAFE_MODE){audit('safe-mode-skip-app-restore',{},'warn');return}const rows=await Storage?.get?.('runtime',installedKey,{preferred:['indexeddb','local','memory']})||[];for(const m of rows){try{manifests.register(m)}catch(e){audit('app-restore-invalid',{id:m?.id,error:e?.message},'warn')}}}catch(e){audit('app-restore-error',{error:e?.message||String(e)},'warn')}}
function registerSystemApp(input){return manifests.register({...input,system:true,runtime:input.runtime||'system'})}
async function installManifest(input){const v=Core.validateManifest(input);if(!v.valid)throw new Error(v.errors.join(','));if(v.manifest.system)throw new Error('cannot-install-system-manifest');const previous=manifests.get(v.manifest.id);manifests.register(v.manifest);try{await persistInstalled()}catch(e){if(previous)manifests.register(previous);else manifests.remove(v.manifest.id);audit('app-install-rollback',{appId:v.manifest.id,error:e?.message||String(e)},'error');throw e}events.emit('apps-changed',manifests.export());audit(previous?'app-updated':'app-installed',{appId:v.manifest.id,version:v.manifest.version,runtime:v.manifest.runtime});return v.manifest}
async function uninstall(appId){const m=manifests.get(appId);if(!m||m.system)return false;manifests.remove(appId);try{await persistInstalled()}catch(e){manifests.register(m);audit('app-uninstall-rollback',{appId,error:e?.message||String(e)},'error');throw e}cancelPromptsForApp(appId,'app-uninstalled');for(const p of processes.findByApp(appId))await stopProcess(p.pid,'app-uninstalled');await grants.revokeApp(appId);Security?.tokens?.revokeApp?.(appId);events.emit('apps-changed',manifests.export());audit('app-uninstalled',{appId},'warn');return true}
function startSystemProcess(appId,metadata={}){const m=manifests.get(appId);if(!m)throw new Error(`unknown-app:${appId}`);const p=processes.spawn(appId,{runtime:'system',metadata});events.emit('process-start',p);audit('process-start',{pid:p.pid,appId,runtime:'system'});return p}
function sendLifecycle(pid,state,reason=''){const port=processPorts.get(pid);try{port?.postMessage({type:'lifecycle',state,reason,time:Date.now()})}catch{}}
function suspendProcess(pid,reason='suspended'){const p=processes.suspend(pid,reason);if(!p)return null;sendLifecycle(pid,'suspended',reason);events.emit('process-state',p);audit('process-suspend',{pid,appId:p.appId,reason});return p}
function resumeProcess(pid){const p=processes.resume(pid);if(!p)return null;sendLifecycle(pid,'running','resume');events.emit('process-state',p);audit('process-resume',{pid,appId:p.appId});return p}
function crashProcess(pid,error='app-crash'){const p=processes.crash(pid,error);if(!p)return null;sendLifecycle(pid,'crashed',error);events.emit('process-state',p);audit('process-crash',{pid,appId:p.appId,error},'error');return p}
function heartbeat(pid,metadata=null){return processes.heartbeat(pid,metadata)}
async function stopProcess(pid,reason='closed'){const p=processes.get(pid);if(!p)return false;cancelPromptsForApp(p.appId,reason,pid);processPorts.delete(pid);const ok=await processes.terminate(pid,reason);if(ok){events.emit('process-stop',{...p,reason});audit('process-stop',{pid,appId:p.appId,reason})}return ok}
function sandboxUrl(appId){const m=manifests.get(appId);if(!m||m.runtime!=='sandbox')throw new Error(`sandbox-app-required:${appId}`);return new URL(`runtime/app-frame.html#${encodeURIComponent(appId)}`,moduleBase).href}
function hasService(manifest,id){return manifest.capabilities.includes('*')||manifest.capabilities.includes(id)}
function appVfsPath(appId,path='.'){const V=globalThis.SuperApiUCOSVFS;if(!V)throw new Error('vfs-unavailable');const root=`/apps/data/${appId}`;const normalized=V.normalize(String(path||'.'));return normalized==='/'?root:V.normalize(`${root}/${normalized.slice(1)}`)}
function mapVfsArgs(appId,method,args){if(['stat','list','mkdir','readText','writeText','remove'].includes(method)){const out=[...args];out[0]=appVfsPath(appId,out[0]);return out}if(['copy','move'].includes(method))return[appVfsPath(appId,args[0]),appVfsPath(appId,args[1])];return args}
async function runAppWorkflow(appId,flow,input,signal){const W=globalThis.SuperApiUCOSWorkflowCore;if(!W)throw new Error('workflow-core-unavailable');const engine=W.createEngine({executeCapability:req=>{const{signal:stepSignal,...cmd}=req;const active=stepSignal||signal;if(active?.aborted)throw active.reason||new DOMException('Aborted','AbortError');return broker.request({appId,...cmd,meta:{...(cmd.meta||{}),pid:input?.__ucosPid||'',ipcRequestId:input?.__ucosIpcRequestId||''}})}});return engine.run(flow,{input,signal})}
function abortError(signal){return signal?.reason||new DOMException('Aborted','AbortError')}
function raceAbort(value,signal){if(!signal)return Promise.resolve(value);if(signal.aborted)return Promise.reject(abortError(signal));return new Promise((resolve,reject)=>{let done=false;const finish=(fn,v)=>{if(done)return;done=true;signal.removeEventListener('abort',onAbort);fn(v)};const onAbort=()=>finish(reject,abortError(signal));signal.addEventListener('abort',onAbort,{once:true});Promise.resolve(value).then(v=>finish(resolve,v),e=>finish(reject,e))})}
const SANDBOX_EVENTS=new Set(['apps-changed','process-state','process-stale']);
function attachSandbox(appId,container,{onReady,onCrash}={}){
 const manifest=manifests.get(appId);if(!manifest)throw new Error(`unknown-app:${appId}`);if(manifest.runtime!=='sandbox')throw new Error('app-is-not-sandboxed');if(globalThis.__UCOS_SAFE_MODE)throw new Error('safe-mode-blocks-sandbox-apps');
 const proc=processes.spawn(appId,{runtime:'sandbox',state:'starting'}),iframe=document.createElement('iframe');iframe.className='ucos-sandbox-app';iframe.setAttribute('sandbox','allow-scripts allow-forms allow-downloads');iframe.setAttribute('referrerpolicy','no-referrer');iframe.src=sandboxUrl(appId);iframe.title=manifest.name;container.appendChild(iframe);
 const channel=new MessageChannel(),inflight=new Map(),subscriptions=new Map();let ready=false;processPorts.set(proc.pid,channel.port1);resources.own(proc.pid,channel.port1,{type:'ipc-port',cleanup:p=>p.close()});resources.own(proc.pid,iframe,{type:'iframe',cleanup:f=>f.remove()});resources.own(proc.pid,inflight,{type:'ipc-inflight',cleanup:map=>{for(const ctl of map.values())try{ctl.abort(new DOMException('Process terminated','AbortError'))}catch{}map.clear()}});resources.own(proc.pid,subscriptions,{type:'ipc-subscriptions',cleanup:map=>{for(const off of map.values())try{off()}catch{}map.clear()}});
 channel.port1.onmessage=async e=>{heartbeat(proc.pid,{lastMessageType:e.data?.type||'unknown'});const msg=e.data||{};if(msg.type==='ready'){ready=true;processes.setState(proc.pid,'running');events.emit('process-state',processes.get(proc.pid));audit('sandbox-ready',{pid:proc.pid,appId});onReady?.(proc);return}if(msg.type==='heartbeat')return;if(msg.type==='crash'){crashProcess(proc.pid,msg.error||'app-crash');onCrash?.(msg);return}if(msg.type==='cancel'&&msg.id){inflight.get(msg.id)?.abort?.(new DOMException('Cancelled','AbortError'));cancelPromptForRequest(appId,proc.pid,String(msg.id),'ipc-cancelled');audit('ipc-cancel',{appId,pid:proc.pid,id:msg.id});return}if(msg.type==='subscribe'){const name=String(msg.event||'');if(!SANDBOX_EVENTS.has(name)||subscriptions.has(name))return;const off=events.on(name,ev=>{const d=ev.detail;if(name==='process-state'&&d?.appId!==appId)return;try{channel.port1.postMessage({type:'event',event:name,detail:d})}catch{}});subscriptions.set(name,off);return}if(msg.type==='unsubscribe'){const name=String(msg.event||''),off=subscriptions.get(name);try{off?.()}catch{}subscriptions.delete(name);return}if(msg.type!=='request'||!msg.id)return;const reply={type:'response',id:msg.id},controller=new AbortController();inflight.set(msg.id,controller);try{
   const ipcQuota=Security?.quotas?.consume?.(`ipc:${appId}`,{context:{appId,service:msg.service}});if(ipcQuota&&!ipcQuota.allowed)throw Object.assign(new Error('ipc-rate-limited'),{retryAfterMs:ipcQuota.retryAfterMs});if(controller.signal.aborted)throw controller.signal.reason;
   if(msg.service==='capability')reply.result=await raceAbort(broker.request({appId,capabilityId:msg.capabilityId,operation:msg.operation,args:msg.args,mode:msg.mode,targetNodeId:msg.targetNodeId,meta:{pid:proc.pid,ipcRequestId:msg.id}}),controller.signal);
   else if(msg.service==='vfs'){if(!hasService(manifest,'system.vfs'))throw new Error('vfs-service-not-declared');const V=globalThis.SuperApiUCOSVFS;if(!V)throw new Error('vfs-unavailable');const method=String(msg.method||'');if(!['stat','list','mkdir','readText','writeText','remove','copy','move','health'].includes(method))throw new Error('vfs-method-denied');if(method==='health')reply.result=V.health();else{await V.mkdir(`/apps/data/${appId}`,{recursive:true});reply.result=await raceAbort(V[method](...mapVfsArgs(appId,method,Array.isArray(msg.args)?msg.args:[])),controller.signal)}}
   else if(msg.service==='workflow'){if(!hasService(manifest,'system.workflow'))throw new Error('workflow-service-not-declared');if(msg.method!=='run')throw new Error('workflow-method-denied');const workflowInput={...(msg.args?.[1]||{}),__ucosPid:proc.pid,__ucosIpcRequestId:String(msg.id)};reply.result=await runAppWorkflow(appId,msg.args?.[0],workflowInput,controller.signal)}
   else if(msg.service==='runtime'){if(msg.method==='heartbeat'){reply.result=heartbeat(proc.pid)||true}else if(msg.method==='health')reply.result={process:processes.get(proc.pid),resources:resources.list(proc.pid)};else throw new Error('runtime-method-denied')}
   else throw new Error('unknown-service');if(controller.signal.aborted)throw controller.signal.reason;reply.ok=true
  }catch(err){reply.ok=false;reply.error=err?.message||String(err);audit('ipc-error',{appId,pid:proc.pid,service:msg.service,error:reply.error},err?.name==='AbortError'?'info':'warn')}finally{inflight.delete(msg.id)}try{channel.port1.postMessage(reply)}catch{}};
 const isPackage=String(manifest.entry).startsWith('package:');const resolvedManifest={...manifest,entry:isPackage?'':new URL(manifest.entry,moduleBase).href};iframe.addEventListener('load',async()=>{try{let entryCode=null;if(isPackage){const Packages=globalThis.SuperApiUCOSPackages;if(!Packages)throw new Error('package-service-unavailable');const verification=await Packages.verify(appId);if(!verification.ok)throw new Error('package-integrity-failed');entryCode=await Packages.getEntryCode(appId)}iframe.contentWindow?.postMessage({type:'ucos:init',manifest:resolvedManifest,pid:proc.pid,entryCode},'*',[channel.port2]);setTimeout(()=>{if(!ready&&processes.get(proc.pid))processes.setState(proc.pid,'starting')},500)}catch(e){crashProcess(proc.pid,e?.message||String(e));onCrash?.({error:e?.message||String(e)})}},{once:true});iframe.addEventListener('error',()=>{crashProcess(proc.pid,'iframe-load-error');onCrash?.({error:'iframe-load-error'})});events.emit('process-start',proc);audit('process-start',{pid:proc.pid,appId,runtime:'sandbox'});return{...proc,iframe,close:()=>stopProcess(proc.pid,'closed'),suspend:reason=>suspendProcess(proc.pid,reason),resume:()=>resumeProcess(proc.pid)}
}
async function requestCapability(appId,capabilityId,options={}){return broker.request({appId,capabilityId,...options})}
async function listGrants(appId=''){return grants.list(appId)}
async function revokeGrant(appId,capabilityId){Security?.tokens?.revokeApp?.(appId);audit('permission-revoked',{appId,capabilityId},'warn');return grants.revoke(appId,capabilityId)}
function checkWatchdog({olderThanMs=90000}={}){const stale=processes.stale({olderThanMs});for(const p of stale){audit('process-stale',{pid:p.pid,appId:p.appId,heartbeatAt:p.heartbeatAt},'warn');events.emit('process-stale',p)}return stale}
function setDocumentLifecycle(){const update=()=>{for(const p of processes.list()){const m=manifests.get(p.appId);if(!m?.lifecycle?.suspendable)continue;if(document.hidden&&p.state==='running')suspendProcess(p.pid,'document-hidden');else if(!document.hidden&&p.state==='suspended'&&p.error==='document-hidden')resumeProcess(p.pid)}if(!document.hidden)checkWatchdog()};document.addEventListener('visibilitychange',update);window.addEventListener('pageshow',update);window.addEventListener('focus',()=>checkWatchdog())}
window.addEventListener('error',e=>audit('window-error',{message:e.message,source:e.filename,line:e.lineno,column:e.colno},'error'));window.addEventListener('unhandledrejection',e=>audit('unhandled-rejection',{reason:e.reason?.message||String(e.reason)},'error'));
setDocumentLifecycle();
const ready=(async()=>{await Security?.ready;await grants.clearSession();await restoreInstalled();try{await globalThis.SuperApiUCOSVFS?.init?.()}catch(e){audit('vfs-init-error',{error:e?.message||String(e)},'warn')}events.emit('ready',{apps:manifests.size()});audit('runtime-ready',{apps:manifests.size(),safeMode:Boolean(globalThis.__UCOS_SAFE_MODE)});return true})();
const api=Object.freeze({core:Core,manifests,grants,resources,processes,events,broker,ready,registerSystemApp,installManifest,uninstall,startSystemProcess,stopProcess,suspendProcess,resumeProcess,crashProcess,heartbeat,checkWatchdog,attachSandbox,requestCapability,resolvePermission,listGrants,revokeGrant,listProcesses:()=>processes.list(),processHistory:()=>processes.history(),health:()=>({version:6,apps:manifests.size(),processes:processes.size(),resources:resources.summary(),pendingPermissions:pendingPrompts.size,safeMode:Boolean(globalThis.__UCOS_SAFE_MODE),security:Security?.health?.()||null})});globalThis.SuperApiUCOSRuntime=api;
})();