(()=>{
'use strict';
if(globalThis.SuperApiUCOSVault)return;
const Security=globalThis.SuperApiUCOSSecurity;
const DB='super-api-ucos-vault-v1',STORE='vault',MASTER='__master__',VERSION=1;
const enc=new TextEncoder(),dec=new TextDecoder();let keyPromise=null;
function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function readRaw(k){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).get(k);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
async function writeRaw(k,v){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function deleteRaw(k){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(k);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function keysRaw(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),r=tx.objectStore(STORE).getAllKeys();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
function nameOf(v){const n=String(v||'').trim();if(!n||n===MASTER||n.length>160)throw new Error('invalid-secret-name');return n}
async function master(){if(keyPromise)return keyPromise;keyPromise=(async()=>{const saved=await readRaw(MASTER);if(saved instanceof CryptoKey&&saved.algorithm?.name==='AES-GCM'&&saved.extractable===false)return saved;const key=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);await writeRaw(MASTER,key);return key})();return keyPromise}
function aad(name){return enc.encode(`UCOS-Vault-v${VERSION}:${name}`)}
async function encrypt(name,value,key=null){key=key||await master();const iv=crypto.getRandomValues(new Uint8Array(12)),plain=enc.encode(JSON.stringify(value)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:aad(name),tagLength:128},key,plain);return{version:VERSION,algorithm:'AES-GCM',iv,cipher,createdAt:Date.now(),updatedAt:Date.now()}}
async function decrypt(name,row,key=null){key=key||await master();if(!row?.cipher||!row?.iv)throw new Error('invalid-secret-record');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:row.iv,additionalData:aad(name),tagLength:128},key,row.cipher);return JSON.parse(dec.decode(plain))}
async function locked(name,fn){if(navigator.locks?.request)return navigator.locks.request(`ucos-vault:${name}`,fn);return fn()}
async function set(name,value,{metadata={}}={}){name=nameOf(name);return locked(name,async()=>{const old=await readRaw(name),row=await encrypt(name,value);row.createdAt=old?.createdAt||row.createdAt;row.metadata={...(old?.metadata||{}),...metadata};await writeRaw(name,row);Security?.auditEvent?.('vault-secret-written',{name,createdAt:row.createdAt,updatedAt:row.updatedAt});return{...row,cipher:undefined,iv:undefined}})}
async function get(name){name=nameOf(name);return locked(name,async()=>{const row=await readRaw(name);if(!row)return null;try{const value=await decrypt(name,row);Security?.auditEvent?.('vault-secret-read',{name});return value}catch(e){Security?.auditEvent?.('vault-decrypt-error',{name,error:e?.message||String(e)},'error');throw new Error('vault-decrypt-failed')}})}
async function remove(name){name=nameOf(name);return locked(name,async()=>{const existed=Boolean(await readRaw(name));await deleteRaw(name);if(existed)Security?.auditEvent?.('vault-secret-deleted',{name},'warn');return existed})}
async function list(){const names=(await keysRaw()).map(String).filter(k=>k!==MASTER);const out=[];for(const name of names){const row=await readRaw(name);out.push({name,version:row?.version||null,algorithm:row?.algorithm||null,createdAt:row?.createdAt||null,updatedAt:row?.updatedAt||null,metadata:row?.metadata||{}})}return out.sort((a,b)=>a.name.localeCompare(b.name))}
async function rotate(){const old=await master(),names=(await keysRaw()).map(String).filter(k=>k!==MASTER),plain=[];for(const name of names){const row=await readRaw(name);plain.push({name,value:await decrypt(name,row,old),metadata:row.metadata||{},createdAt:row.createdAt})}const next=await crypto.subtle.generateKey({name:'AES-GCM',length:256},false,['encrypt','decrypt']);for(const item of plain){const row=await encrypt(item.name,item.value,next);row.metadata=item.metadata;row.createdAt=item.createdAt||row.createdAt;await writeRaw(item.name,row)}await writeRaw(MASTER,next);keyPromise=Promise.resolve(next);Security?.auditEvent?.('vault-master-rotated',{secrets:plain.length},'warn');return{rotated:true,secrets:plain.length}}
async function clear(){for(const name of (await keysRaw()).map(String).filter(k=>k!==MASTER))await deleteRaw(name);Security?.auditEvent?.('vault-cleared',{},'warn');return true}
async function health(){const k=await master();return{version:VERSION,available:Boolean(crypto.subtle&&indexedDB),algorithm:k.algorithm?.name||null,keyExtractable:k.extractable,usage:['encrypt','decrypt'],secrets:(await keysRaw()).filter(k=>String(k)!==MASTER).length}}
const ready=(async()=>{const h=await health();Security?.auditEvent?.('vault-ready',{algorithm:h.algorithm,keyExtractable:h.keyExtractable});return h})();
const api=Object.freeze({ready,set,get,remove,list,rotate,clear,health});globalThis.SuperApiUCOSVault=api;
})();
