(()=>{
'use strict';
if(globalThis.SuperApiUCOSUpdate)return;
const events=new EventTarget(),Security=globalThis.SuperApiUCOSSecurity;let registration=null,waiting=false,installing=false,lastCheck=0;
function emit(type,detail){events.dispatchEvent(new CustomEvent(type,{detail}))}
async function inspect(){if(!('serviceWorker'in navigator))return{supported:false};registration=registration||await navigator.serviceWorker.getRegistration('./')||await navigator.serviceWorker.register('./sw.js');waiting=Boolean(registration.waiting);installing=Boolean(registration.installing);return{supported:true,waiting,installing,active:Boolean(registration.active),controller:Boolean(navigator.serviceWorker.controller),lastCheck}}
function watch(reg){if(!reg||reg.__ucosV5Watched)return;try{Object.defineProperty(reg,'__ucosV5Watched',{value:true})}catch{};reg.addEventListener('updatefound',()=>{installing=true;const w=reg.installing;Security?.auditEvent?.('update-found',{});emit('updatefound',{});w?.addEventListener('statechange',()=>{installing=w.state==='installing';if(w.state==='installed'&&navigator.serviceWorker.controller){waiting=true;Security?.auditEvent?.('update-ready',{});emit('ready',{waiting:true})}})})}
async function check(){if(!('serviceWorker'in navigator))throw new Error('service-worker-unavailable');registration=registration||await navigator.serviceWorker.register('./sw.js');watch(registration);lastCheck=Date.now();await registration.update();return inspect()}
async function activate({reload=true}={}){registration=registration||await navigator.serviceWorker.getRegistration('./');const worker=registration?.waiting;if(!worker)return false;Security?.auditEvent?.('update-activate-request',{});return new Promise(resolve=>{let done=false;const finish=v=>{if(done)return;done=true;resolve(v);if(v&&reload)setTimeout(()=>location.reload(),50)};const timer=setTimeout(()=>finish(false),5000);navigator.serviceWorker.addEventListener('controllerchange',()=>{clearTimeout(timer);finish(true)},{once:true});worker.postMessage({type:'ucos:activate-update'})})}
async function ready(){if(!('serviceWorker'in navigator))return false;registration=await navigator.serviceWorker.register('./sw.js');watch(registration);await navigator.serviceWorker.ready.catch(()=>{});navigator.serviceWorker.addEventListener('controllerchange',()=>{waiting=false;emit('activated',{})});await inspect();return true}
const readyPromise=ready().catch(e=>{Security?.auditEvent?.('update-manager-error',{error:e?.message||String(e)},'warn');return false});
const api=Object.freeze({events,ready:readyPromise,check,activate,inspect,health:()=>({supported:'serviceWorker'in navigator,waiting,installing,lastCheck})});globalThis.SuperApiUCOSUpdate=api;
})();
