(()=>{
'use strict';
const Core=globalThis.SuperApiUCOSFabricCore,CapOS=globalThis.SuperApiCapabilityOS,LegacyActions=globalThis.SuperApiLegacyActions;
if(!Core||!CapOS){console.error('UCOS Fabric requires capability-os-core/runtime and ucos-fabric-core');return}
if(globalThis.SuperApiUCOS)return;
const capabilities=Core.createCapabilityRegistry(),providers=Core.createProviderRegistry(),transports=Core.createTransportRegistry();
const pendingPings=new Map(),pendingRequests=new Map(),nodeChannels=new Map(),channelNodes=new WeakMap(),events=new EventTarget();
const started=performance.now(),telemetry=[],MAX_TELEMETRY=400;let channelSetInstalled=false,observedSet=null,actionObserver=null;
function sessionNodeId(){const k='super-api-ucos-node-id';try{let v=sessionStorage.getItem(k);if(!v){v=Core.id('node');sessionStorage.setItem(k,v)}return v}catch{return Core.id('node')}}
const localNodeId=sessionNodeId(),nodes=Core.createNodeRegistry({id:localNodeId,label:`This device • ${navigator.platform||'Browser'}`,kind:'browser',local:true,online:true,metadata:{userAgent:navigator.userAgent,language:navigator.language}}),clone=Core.clone;
function emit(type,detail){events.dispatchEvent(new CustomEvent(type,{detail:clone(detail)}))}
function record(row){telemetry.unshift({...clone(row),time:new Date().toISOString()});if(telemetry.length>MAX_TELEMETRY)telemetry.length=MAX_TELEMETRY;emit('telemetry',row)}
function secure(){return globalThis.isSecureContext===true}
function isHost(){const h=document.querySelector('#hostBtn'),c=document.querySelector('#controllerBtn');return!!h?.classList.contains('primary')&&!c?.classList.contains('primary')}
function authorized(){return Boolean(document.querySelector('#allowRequests')?.checked)}
function openChannels(){return[...(globalThis.__superApiTrackedChannels||[])].filter(ch=>ch?.readyState==='open')}
function currentChannel(){const list=openChannels();return list[list.length-1]||null}
function channelForNode(nodeId){return nodeChannels.get(String(nodeId||''))||null}
function actionName(capability){return capability?.metadata?.action||String(capability?.id||'').replace(/^action:/,'')}
function operationAllowed(capability,operation){return!capability?.operations?.length||capability.operations.includes(operation)}
function abortError(signal){return signal?.reason||new DOMException('Aborted','AbortError')}
function checkAbort(signal){if(signal?.aborted)throw abortError(signal)}
function nativeAvailable(action){switch(action){case'camera':case'microphone':return Boolean(navigator.mediaDevices?.getUserMedia);case'geolocation':return Boolean(navigator.geolocation);case'clipboard-read':case'clipboard-write':return Boolean(navigator.clipboard);case'file-open':return Boolean(globalThis.showOpenFilePicker||document.createElement);case'directory':return Boolean(globalThis.showDirectoryPicker);case'notifications':return Boolean(globalThis.Notification);case'share':return Boolean(navigator.share);case'battery':return Boolean(navigator.getBattery);default:return true}}
function legacySupport(action){if(!LegacyActions?.has?.(action))return null;try{return LegacyActions.support?.(action)||{known:true,supported:true}}catch{return{known:true,supported:true}}}
function localStatusFor(c){const action=actionName(c);if(nativeBasic.has(action))return nativeAvailable(action)?'available':'unsupported';const legacy=legacySupport(action);if(legacy)return legacy.supported===false?'unsupported':'available';if(action.startsWith('ext:'))return typeof globalThis.SUPER_API_EXT_HANDLE==='function'?'available':'provider-missing';return'provider-missing'}
function syncCapabilities(notify=false){CapOS.discoverActions?.();for(const c of CapOS.catalog?.()||[]){const status=localStatusFor(c);capabilities.register({...c,status,metadata:{...(c.metadata||{}),compatibilitySource:'SuperApiCapabilityOS',localProviderStatus:status}})}const list=capabilities.export();nodes.upsert({...(nodes.get(localNodeId)||{}),id:localNodeId,local:true,online:navigator.onLine,capabilities:list.filter(c=>c.status==='available').map(c=>c.id),capabilityDetails:list,lastSeen:Date.now()});if(notify)emit('capabilities',capabilities.summary());return list}
async function probeMedia(constraints,signal){checkAbort(signal);const stream=await navigator.mediaDevices.getUserMedia(constraints);if(signal?.aborted){for(const t of stream.getTracks())try{t.stop()}catch{}throw abortError(signal)}const result={mediaProbe:true,tracks:stream.getTracks().map(t=>({kind:t.kind,label:t.label,readyState:t.readyState,enabled:t.enabled,muted:t.muted})),stopped:true,note:'UCOS basic provider performs a bounded capability probe. Use the Camera app or Developer Lab for persistent preview/streaming.'};for(const track of stream.getTracks())try{track.stop()}catch{}return result}
const nativeBasic=new Map([
 ['environment-info',async(_a,signal)=>{checkAbort(signal);return{secureContext:secure(),online:navigator.onLine,language:navigator.language,languages:navigator.languages,platform:navigator.platform,hardwareConcurrency:navigator.hardwareConcurrency,maxTouchPoints:navigator.maxTouchPoints,visibility:document.visibilityState,url:location.href}}],
 ['storage-estimate',async(_a,signal)=>{checkAbort(signal);if(!navigator.storage?.estimate)throw new Error('StorageManager.estimate unavailable');const x=await navigator.storage.estimate();checkAbort(signal);return{usage:x.usage,quota:x.quota,usageDetails:x.usageDetails,persisted:await navigator.storage.persisted?.()}}],
 ['permissions',async(_a,signal)=>{checkAbort(signal);if(!navigator.permissions)throw new Error('Permissions API unavailable');const out={};for(const name of ['geolocation','camera','microphone','notifications','clipboard-read','clipboard-write']){checkAbort(signal);try{out[name]=(await navigator.permissions.query({name})).state}catch{out[name]='query unsupported'}}return out}],
 ['network',async(_a,signal)=>{checkAbort(signal);const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;return c?{online:navigator.onLine,type:c.type,effectiveType:c.effectiveType,downlink:c.downlink,rtt:c.rtt,saveData:c.saveData}:{online:navigator.onLine,connectionAPI:false}}],
 ['battery',async(_a,signal)=>{checkAbort(signal);if(!navigator.getBattery)throw new Error('Battery Status API unavailable');const b=await navigator.getBattery();checkAbort(signal);return{charging:b.charging,level:b.level,chargingTime:b.chargingTime,dischargingTime:b.dischargingTime}}],
 ['crypto',async(_a,signal)=>{checkAbort(signal);const d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode('super-api-ucos'));checkAbort(signal);return{sha256:[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,'0')).join(''),random:[...crypto.getRandomValues(new Uint32Array(4))]}}],
 ['geolocation',async(_a,signal)=>new Promise((resolve,reject)=>{checkAbort(signal);let settled=false;const finish=(fn,v)=>{if(settled)return;settled=true;signal?.removeEventListener('abort',onAbort);fn(v)},onAbort=()=>finish(reject,abortError(signal));signal?.addEventListener('abort',onAbort,{once:true});navigator.geolocation?.getCurrentPosition(p=>finish(resolve,{latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,timestamp:p.timestamp}),e=>finish(reject,e),{enableHighAccuracy:true,timeout:12000})||finish(reject,new Error('Geolocation unavailable'))})],
 ['clipboard-read',async(_a,signal)=>{checkAbort(signal);const text=await navigator.clipboard.readText();checkAbort(signal);return{text}}],
 ['clipboard-write',async(args,signal)=>{checkAbort(signal);await navigator.clipboard.writeText(String(args?.text??`Super API UCOS ${new Date().toISOString()}`));checkAbort(signal);return{written:true}}],
 ['camera',async(_a,signal)=>probeMedia({video:true,audio:false},signal)],['microphone',async(_a,signal)=>probeMedia({audio:true,video:false},signal)],
 ['file-open',async(_a,signal)=>{checkAbort(signal);if(globalThis.showOpenFilePicker){const[h]=await showOpenFilePicker();checkAbort(signal);const f=await h.getFile();return{name:f.name,size:f.size,type:f.type,lastModified:f.lastModified}}const input=document.createElement('input');input.type='file';return new Promise((resolve,reject)=>{const onAbort=()=>{input.remove();reject(abortError(signal))};signal?.addEventListener('abort',onAbort,{once:true});input.onchange=()=>{signal?.removeEventListener('abort',onAbort);const f=input.files?.[0];input.remove();f?resolve({name:f.name,size:f.size,type:f.type,lastModified:f.lastModified}):reject(new Error('No file selected'))};input.click()})}],
 ['directory',async(_a,signal)=>{checkAbort(signal);if(!globalThis.showDirectoryPicker)throw new Error('Directory picker unavailable');const h=await showDirectoryPicker();checkAbort(signal);return{name:h.name,kind:h.kind}}],
 ['notifications',async(args,signal)=>{checkAbort(signal);if(!globalThis.Notification)throw new Error('Notifications unavailable');const permission=await Notification.requestPermission();checkAbort(signal);if(permission==='granted'){try{const reg=await navigator.serviceWorker?.ready;await reg?.showNotification?.(String(args?.title||'Super API UCOS'),{body:String(args?.body||'Notification capability is working.'),tag:'super-api-ucos-test'})}catch{}}return{permission,shown:permission==='granted'}}],
 ['share',async(args,signal)=>{checkAbort(signal);if(!navigator.share)throw new Error('Web Share unavailable');await navigator.share({title:args?.title||'Super API UCOS',text:args?.text||'Universal Capability Fabric',url:args?.url||location.href});checkAbort(signal);return{shared:true}}],
 ['vibration',async(args,signal)=>{checkAbort(signal);return{accepted:Boolean(navigator.vibrate?.(args?.pattern||100))}}]
]);
providers.register({id:'browser-native-basic',label:'Browser Native Provider',priority:20,local:true,supports(capability,operation){return operationAllowed(capability,operation)&&nativeBasic.has(actionName(capability))&&nativeAvailable(actionName(capability))},async execute(capability,command,ctx={}){const fn=nativeBasic.get(actionName(capability));if(!fn)throw new Error('Native basic adapter unavailable');return fn(command.args||{},ctx.signal||command.signal)},health:()=>({available:true,actions:[...nativeBasic.keys()]})});
providers.register({id:'legacy-main-local',label:'Primary Super API Action Provider',priority:30,local:true,supports(capability,operation){const action=actionName(capability),support=legacySupport(action);return operationAllowed(capability,operation)&&!nativeBasic.has(action)&&Boolean(support&&support.supported!==false)},async execute(capability,command,ctx={}){const signal=ctx.signal||command.signal;checkAbort(signal);if(!LegacyActions?.execute)throw new Error('Primary action bridge unavailable');const result=await LegacyActions.execute(actionName(capability),command.args||{});checkAbort(signal);return result},health:()=>({available:Boolean(LegacyActions),actions:LegacyActions?.list?.().length||0})});
providers.register({id:'legacy-extension-local',label:'Existing extension action bus',priority:50,local:true,supports(capability,operation){return operationAllowed(capability,operation)&&actionName(capability).startsWith('ext:')&&typeof globalThis.SUPER_API_EXT_HANDLE==='function'},execute:async(capability,command,ctx={})=>{checkAbort(ctx.signal||command.signal);const env=await CapOS.execute({capabilityId:capability.id,operation:'execute',args:command.args||{},mode:'local',meta:command.meta||{}});checkAbort(ctx.signal||command.signal);return env.result},health:()=>({available:typeof globalThis.SUPER_API_EXT_HANDLE==='function'})});
function awaitRequest(channel,id,timeout=30000,signal=null){if(pendingRequests.has(id))return Promise.reject(new Error(`duplicate-request:${id}`));if(signal?.aborted)return Promise.reject(abortError(signal));return new Promise((resolve,reject)=>{let settled=false;const cleanup=()=>{clearTimeout(timer);signal?.removeEventListener('abort',onAbort);pendingRequests.delete(id)},finish=(fn,v)=>{if(settled)return;settled=true;cleanup();fn(v)},onAbort=()=>{try{channel.send(JSON.stringify({type:'cancel',id}))}catch{}finish(reject,abortError(signal))},timer=setTimeout(()=>finish(reject,new Error('Peer command timed out')),Math.min(120000,Math.max(100,Number(timeout)||30000)));signal?.addEventListener('abort',onAbort,{once:true});pendingRequests.set(id,{channel,resolve:v=>finish(resolve,v),reject:e=>finish(reject,e),cancel:onAbort})})}
async function requestOnChannel(command,channel){if(!channel||channel.readyState!=='open')throw new Error('Target peer channel unavailable');const capability=capabilities.get(command.capabilityId);if(!capability)throw new Error(`Unknown capability ${command.capabilityId}`);const action=actionName(capability);if(!action)throw new Error('Capability has no peer action');const wait=awaitRequest(channel,command.id,command.meta?.timeout,command.signal);try{channel.send(JSON.stringify({type:'request',action,id:command.id,params:command.args??{}}))}catch(e){pendingRequests.get(command.id)?.reject(e)}return wait}
transports.register({id:'webrtc-compat',label:'Super API WebRTC node transport',kind:'webrtc',priority:10,available:ctx=>ctx?.targetNodeId?Boolean(channelForNode(ctx.targetNodeId)?.readyState==='open'):openChannels().length>0,request:(command,ctx={})=>requestOnChannel({...command,signal:ctx.signal||command.signal},ctx.channel||channelForNode(command.targetNodeId)||currentChannel()),notify(message,ctx={}){const ch=ctx.channel||channelForNode(ctx.targetNodeId)||currentChannel();if(!ch)throw new Error('No open paired-peer data channel');ch.send(JSON.stringify(message));return true}});
transports.register({id:'loopback',label:'Local loopback',kind:'local',priority:1,available:()=>true,request:(command,ctx={})=>executeLocal({...command,signal:ctx.signal||command.signal})});
function localProvidersFor(capabilityId,operation='execute'){syncCapabilities();const capability=capabilities.get(capabilityId);if(!capability)return[];return providers.resolve(capability,operation,{local:true})}
async function executeLocal(request){syncCapabilities();const validation=Core.validateRequest(request);if(!validation.valid)throw new Error(validation.errors.join(', '));const command=validation.request,capability=capabilities.get(command.capabilityId);checkAbort(command.signal);if(!capability)throw new Error(`Unknown capability ${command.capabilityId}`);if(capability.operations?.length&&!capability.operations.includes(command.operation))throw new Error(`Operation ${command.operation} is not supported by ${capability.id}`);const candidates=providers.resolve(capability,command.operation,{local:true,signal:command.signal});if(!candidates.length)throw new Error(`No UCOS local provider for ${capability.id}; this capability may be unsupported in the current browser or require external infrastructure.`);let lastError=null;for(const provider of candidates){const t=performance.now();try{checkAbort(command.signal);const result=await provider.execute(capability,command,{node:nodes.get(localNodeId),signal:command.signal});checkAbort(command.signal);const env=Core.executionEnvelope({requestId:command.id,capabilityId:capability.id,operation:command.operation,status:'available',providerId:provider.id,nodeId:localNodeId,result,durationMs:performance.now()-t});record(env);return env}catch(e){lastError=e;record(Core.executionEnvelope({requestId:command.id,capabilityId:capability.id,operation:command.operation,status:'error',providerId:provider.id,nodeId:localNodeId,error:e?.message||String(e),durationMs:performance.now()-t}));if(e?.name==='AbortError')break}}throw lastError||new Error('Local execution failed')}
async function executeRemote(request){syncCapabilities();installChannelObserver();const validation=Core.validateRequest(request);if(!validation.valid)throw new Error(validation.errors.join(', '));const command=validation.request,capability=capabilities.get(command.capabilityId);checkAbort(command.signal);if(!capability)throw new Error(`Unknown capability ${command.capabilityId}`);if(capability.operations?.length&&!capability.operations.includes(command.operation))throw new Error(`Operation ${command.operation} is not supported by ${capability.id}`);if(capability.remoteAllowed===false)throw new Error(`Capability ${capability.id} does not allow remote execution`);let target=command.targetNodeId,channel=target?channelForNode(target):null;if(target&&!channel)throw new Error(`Target node is not connected: ${target}`);if(!channel){const candidate=route(command.capabilityId,{preferLocal:false}).find(x=>!x.local&&x.node.online&&channelForNode(x.node.id));if(candidate){target=candidate.node.id;channel=channelForNode(target)}}if(!channel){channel=currentChannel();const mapped=channel?channelNodes.get(channel):null;if(mapped)target=mapped}if(!channel)throw new Error('No remote peer transport is currently available');const transport=transports.get('webrtc-compat'),t=performance.now();try{const result=await transport.request(command,{channel,targetNodeId:target,signal:command.signal});checkAbort(command.signal);const nodeId=target||'paired-peer',env=Core.executionEnvelope({requestId:command.id,capabilityId:capability.id,operation:command.operation,status:'available',transportId:transport.id,nodeId,result,durationMs:performance.now()-t});record(env);return env}catch(e){const env=Core.executionEnvelope({requestId:command.id,capabilityId:capability.id,operation:command.operation,status:'error',transportId:transport.id,nodeId:target||'paired-peer',error:e?.message||String(e),durationMs:performance.now()-t});record(env);throw Object.assign(e instanceof Error?e:new Error(env.error),{envelope:env})}}
async function execute(input={}){const validation=Core.validateRequest(input);if(!validation.valid)throw new Error(validation.errors.join(', '));const command=validation.request;checkAbort(command.signal);if(command.mode==='local')return executeLocal(command);if(command.mode==='peer'||command.mode==='remote')return executeRemote(command);if(command.targetNodeId&&command.targetNodeId!==localNodeId)return executeRemote(command);const localCandidates=localProvidersFor(command.capabilityId,command.operation);if(localCandidates.length)return executeLocal(command);if(openChannels().length)return executeRemote(command);return executeLocal(command)}
function advertisementMessage(){syncCapabilities();return Core.advertisement(nodes.get(localNodeId),capabilities.export())}
function sendAdvertisement(channel=null){const targets=channel?[channel]:openChannels();let count=0;for(const ch of targets){if(ch?.readyState!=='open')continue;try{ch.send(JSON.stringify(advertisementMessage()));count++}catch{}}return count>0}
function associateNode(channel,node){if(!channel||!node?.id)return;const old=channelNodes.get(channel);if(old&&old!==node.id&&nodeChannels.get(old)===channel)nodeChannels.delete(old);channelNodes.set(channel,node.id);nodeChannels.set(node.id,channel);nodes.upsert({...node,local:false,online:true,transportId:'webrtc-compat',lastSeen:Date.now()})}
function settleRequest(msg,channel){const p=pendingRequests.get(msg?.id);if(!p||p.channel!==channel)return false;if(msg.type==='error')p.reject(new Error(msg.error||'Peer command failed'));else p.resolve(msg.result??msg);return true}
function bindChannel(channel){if(!channel||channel.__superApiUCOSBound)return channel;try{Object.defineProperty(channel,'__superApiUCOSBound',{value:true,configurable:true})}catch{return channel}const receive=event=>{let msg;try{msg=JSON.parse(event.data)}catch{return}if((msg?.type==='result'||msg?.type==='error')&&settleRequest(msg,channel))return;if(msg?.type==='ucos:advertise'&&msg.node){associateNode(channel,msg.node);emit('nodes',nodes.export());return}if(msg?.type==='ucos:hello'&&msg.node){associateNode(channel,msg.node);sendAdvertisement(channel);emit('nodes',nodes.export());return}if(msg?.type==='ucos:ping'){try{channel.send(JSON.stringify({type:'ucos:pong',id:msg.id,nodeId:localNodeId,time:Date.now()}))}catch{}return}if(msg?.type==='ucos:pong'&&pendingPings.has(msg.id)){const p=pendingPings.get(msg.id);if(p.channel!==channel)return;pendingPings.delete(msg.id);p.resolve(msg)}};channel.addEventListener?.('message',receive);const hello=()=>{try{channel.send(JSON.stringify({type:'ucos:hello',node:{id:localNodeId,label:nodes.get(localNodeId)?.label,kind:'browser',online:true,lastSeen:Date.now()}}));sendAdvertisement(channel)}catch{}};channel.addEventListener?.('open',hello,{once:true});channel.addEventListener?.('close',()=>{const nodeId=channelNodes.get(channel);if(nodeId&&nodeChannels.get(nodeId)===channel){nodeChannels.delete(nodeId);channelNodes.delete(channel);const n=nodes.get(nodeId);if(n)nodes.upsert({...n,online:false,lastSeen:Date.now()})}for(const[id,p]of pendingRequests)if(p.channel===channel)p.reject(new Error('Peer channel closed before response'));for(const[id,p]of pendingPings)if(p.channel===channel){pendingPings.delete(id);p.reject(new Error('Peer channel closed before pong'))}emit('nodes',nodes.export())},{once:true});if(channel.readyState==='open')queueMicrotask(hello);return channel}
function installChannelObserver(){const current=globalThis.__superApiTrackedChannels;if(channelSetInstalled&&current===observedSet)return;const Existing=current instanceof Set?current:new Set();class ObservableChannelSet extends Set{add(value){super.add(value);bindChannel(value);return this}}const next=new ObservableChannelSet(Existing);observedSet=next;globalThis.__superApiTrackedChannels=next;channelSetInstalled=true;for(const ch of next)bindChannel(ch)}
async function ping(targetOrTimeout=2500,maybeTimeout=2500){installChannelObserver();const targetNodeId=typeof targetOrTimeout==='string'?targetOrTimeout:'',timeout=typeof targetOrTimeout==='number'?targetOrTimeout:maybeTimeout,ch=targetNodeId?channelForNode(targetNodeId):currentChannel();if(!ch)throw new Error(targetNodeId?`Target node is not connected: ${targetNodeId}`:'No open peer channel');const id=Core.id('ping'),promise=new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pendingPings.delete(id);reject(new Error('Peer ping timed out'))},timeout);pendingPings.set(id,{channel,resolve:v=>{clearTimeout(timer);resolve(v)},reject:e=>{clearTimeout(timer);reject(e)}})});ch.send(JSON.stringify({type:'ucos:ping',id,nodeId:localNodeId,time:Date.now()}));return promise}
function route(capabilityId,{preferLocal=true,targetNodeId=null}={}){syncCapabilities();const capability=capabilities.get(capabilityId);if(!capability)return[];return Core.routeCandidates({capability,nodes:nodes.list(),preferLocal,targetNodeId}).map(x=>({...x,connected:x.local||Boolean(channelForNode(x.node.id))}))}
function health(){syncCapabilities();installChannelObserver();return{version:'6.5',architecture:'Universal Capability Fabric',uptimeMs:Math.round(performance.now()-started),localNodeId,capabilities:capabilities.summary(),providers:providers.list().map(p=>({id:p.id,label:p.label,priority:p.priority})),transports:transports.list().map(t=>({id:t.id,label:t.label,kind:t.kind,available:Boolean(t.available?.())})),nodes:nodes.export(),peerConnected:openChannels().length>0,connectedPeerNodes:[...nodeChannels.keys()],openPeerChannels:openChannels().length,sessionAuthorized:authorized(),controlledPeer:isHost(),secureContext:secure(),storage:globalThis.SuperApiUCOSStorage?.health?.()||null,telemetry:telemetry.length,pendingRemoteRequests:pendingRequests.size,primaryActions:LegacyActions?.list?.().length||0,providerAccurateStatus:true,cancellationPropagation:true,legacyLabPreserved:true}}
function refresh(){syncCapabilities(true);installChannelObserver();sendAdvertisement();const snapshot=health();emit('refresh',snapshot);return snapshot}
installChannelObserver();syncCapabilities(true);for(const id of['hostBtn','controllerBtn','allowRequests'])document.querySelector(`#${id}`)?.addEventListener(id==='allowRequests'?'change':'click',()=>queueMicrotask(refresh));window.addEventListener('online',refresh);window.addEventListener('offline',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});const actionSelect=document.querySelector('#remoteAction');if(actionSelect){actionObserver=new MutationObserver(()=>queueMicrotask(refresh));actionObserver.observe(actionSelect,{childList:true})}
const api=Object.freeze({core:Core,capabilities,providers,transports,nodes,events,telemetry,execute,executeLocal,executeRemote,route,health,refresh,ping,sendAdvertisement,channelForNode,registerProvider:p=>providers.register(p),registerTransport:t=>transports.register(t),localNodeId});globalThis.SuperApiUCOS=api;queueMicrotask(()=>emit('ready',health()));
})();