const CACHE='super-api-ucos-v26';
const PREVIOUS='super-api-ucos-v25';
const CORE=['./','./index.html','./app.js','./catalog.js','./peer-hook.js','./session-consent.js','./api-extensions.js','./deep-api-tests.js','./session-bootstrap.js','./runtime-surface.js','./emerging-apis.js','./realm-scanners.js','./mdn-live-index.js','./interface-harness.js','./latest-platform.js','./modules/realm-rpc.js','./modules/universal-core.js','./modules/universal-api.js','./modules/universal-api-v2.js','./modules/network-signal-core.js','./modules/network-signal.js','./modules/wireless-radio-core.js','./modules/wireless-radio.js','./modules/capability-os-core.js','./modules/capability-os.js','./modules/ucos-fabric-core.js','./modules/ucos-storage.js','./modules/ucos-fabric.js','./modules/ucos-lifecycle.js','./modules/ucos-security-core.js','./modules/ucos-security.js','./modules/ucos-vault.js','./modules/ucos-secure-peer.js','./modules/ucos-runtime-core.js','./modules/ucos-vfs.js','./modules/ucos-package-core.js','./modules/ucos-packages.js','./modules/ucos-workflow-core.js','./modules/ucos-workflows.js','./modules/ucos-runtime.js','./modules/ucos-shell.js','./modules/ucos-v4-integration.js','./modules/ucos-update.js','./modules/ucos-v5-integration.js','./modules/ucos-v6-integration.js','./modules/ucos-jobs.js','./runtime/app-frame.html','./runtime/app-frame.js','./workers/realm-rpc-sw.js','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)));});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const k of await caches.keys()){if(k.startsWith('super-api-peer-lab-'))await caches.delete(k);else if(k.startsWith('super-api-ucos-')&&k!==CACHE&&k!==PREVIOUS)await caches.delete(k)}await self.clients.claim();})());});
async function networkFirst(req){try{const response=await fetch(req);if(response.ok){const cache=await caches.open(CACHE);await cache.put(req,response.clone())}return response}catch(error){const cached=await caches.match(req);if(cached)return cached;throw error}}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;if(req.mode==='navigate'){event.respondWith(fetch(req).then(r=>{const copy=r.clone();caches.open(CACHE).then(c=>c.put('./index.html',copy));return r}).catch(async()=>await caches.match('./index.html')||await caches.match('./')));return}if(req.destination==='script'||url.pathname.endsWith('.js')){event.respondWith(networkFirst(req));return}event.respondWith(caches.match(req).then(cached=>{const network=fetch(req).then(r=>{if(r.ok)caches.open(CACHE).then(c=>c.put(req,r.clone()));return r}).catch(()=>cached);return cached||network}))});
const JOB_DB='super-api-ucos-sw',JOB_STORE='jobs',SUPPORTED_JOB_TYPES=new Set(['notify-clients']),MAX_JOB_BYTES=64*1024;
let jobDbPromise=null;
function openJobDb(){if(jobDbPromise)return jobDbPromise;jobDbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(JOB_DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(JOB_STORE))r.result.createObjectStore(JOB_STORE,{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{jobDbPromise=null;reject(r.error||new Error('job-db-open-failed'))};r.onblocked=()=>{jobDbPromise=null;reject(new Error('job-db-open-blocked'))}});return jobDbPromise}
function validateJob(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('invalid-job');const type=String(input.type||'');if(!SUPPORTED_JOB_TYPES.has(type))throw new Error('unsupported-job-type');const id=String(input.id||`job-${Date.now()}-${Math.random().toString(36).slice(2)}`);if(!id||id.length>160)throw new Error('invalid-job-id');const job={...input,id,type,queuedAt:Date.now()};let bytes=Infinity;try{bytes=new TextEncoder().encode(JSON.stringify(job)).byteLength}catch{}if(bytes>MAX_JOB_BYTES)throw new Error('job-too-large');return job}
async function putJob(job){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).put(job);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function getJobs(){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readonly'),r=tx.objectStore(JOB_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function deleteJob(db,id){const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).delete(id);return new Promise((resolve,reject)=>{tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function drainJobs(){const db=await openJobDb(),jobs=await getJobs();let completed=0;for(const job of jobs){if(!SUPPORTED_JOB_TYPES.has(job?.type)){await deleteJob(db,job.id);completed++;continue}if(job.type==='notify-clients'){const windows=await clients.matchAll({type:'window',includeUncontrolled:true});if(!windows.length)continue;for(const c of windows)c.postMessage({type:'ucos:background-job',job});await deleteJob(db,job.id);completed++}}return completed}
self.addEventListener('sync',event=>{if(event.tag==='super-api-sync'||event.tag==='ucos-jobs')event.waitUntil(drainJobs())});
function realmMembers(obj,maxDepth=6){const seen=new Set(),out=[];let p=obj,depth=0;while(p&&depth++<maxDepth){let keys=[];try{keys=Reflect.ownKeys(p)}catch{break}for(const key of keys){const name=typeof key==='symbol'?key.toString():String(key);if(name==='constructor'||seen.has(name))continue;seen.add(name);let d;try{d=Object.getOwnPropertyDescriptor(p,key)}catch{}out.push({name,kind:typeof d?.value==='function'?'method':(d?.get||d?.set?'accessor':'property'),depth:depth-1})}try{p=Object.getPrototypeOf(p)}catch{break}}return out.sort((a,b)=>a.name.localeCompare(b.name))}
self.addEventListener('message',event=>{const port=event.ports?.[0],data=event.data||{};
 if(data.type==='ucos:activate-update'){self.skipWaiting();port?.postMessage({ok:true,activating:true,cache:CACHE});return}
 if(data.type==='ucos:cache-status'){event.waitUntil(caches.keys().then(keys=>port?.postMessage({ok:true,current:CACHE,previous:PREVIOUS,caches:keys.filter(k=>k.startsWith('super-api-ucos-'))})));return}
 if(data.type==='super-api-ping'){port?.postMessage({type:'super-api-pong',received:data.time,responded:Date.now(),cache:CACHE});return}
 if(data.type==='super-api-realm-scan'){port?.postMessage({realm:'ServiceWorkerGlobalScope',constructor:self.constructor?.name||null,cache:CACHE,globals:Object.getOwnPropertyNames(self).sort(),members:realmMembers(self),registration:realmMembers(self.registration),clients:realmMembers(self.clients),navigator:realmMembers(self.navigator),caches:realmMembers(self.caches),crypto:realmMembers(self.crypto),performance:realmMembers(self.performance)});return}
 if(data.type==='ucos:queue-job'&&data.job){event.waitUntil((async()=>{try{const job=validateJob(data.job);await putJob(job);port?.postMessage({ok:true,id:job.id})}catch(error){port?.postMessage({ok:false,error:error?.message||String(error)})}})());return}
 if(data.type==='ucos:drain-jobs'){event.waitUntil(drainJobs().then(count=>port?.postMessage({ok:true,count})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})))}
});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>ws[0]?.focus()||clients.openWindow('./')))});