const CACHE='super-api-ucos-v27';
const PREVIOUS='super-api-ucos-v26';
const CORE=['./','./index.html','./app.js','./catalog.js','./peer-hook.js','./session-consent.js','./api-extensions.js','./deep-api-tests.js','./session-bootstrap.js','./runtime-surface.js','./emerging-apis.js','./realm-scanners.js','./mdn-live-index.js','./interface-harness.js','./latest-platform.js','./modules/realm-rpc.js','./modules/universal-core.js','./modules/universal-api.js','./modules/universal-api-v2.js','./modules/network-signal-core.js','./modules/network-signal.js','./modules/wireless-radio-core.js','./modules/wireless-radio.js','./modules/capability-os-core.js','./modules/capability-os.js','./modules/ucos-fabric-core.js','./modules/ucos-storage.js','./modules/ucos-fabric.js','./modules/ucos-lifecycle.js','./modules/ucos-security-core.js','./modules/ucos-security.js','./modules/ucos-vault.js','./modules/ucos-secure-peer.js','./modules/ucos-runtime-core.js','./modules/ucos-vfs.js','./modules/ucos-package-core.js','./modules/ucos-packages.js','./modules/ucos-workflow-core.js','./modules/ucos-workflows.js','./modules/ucos-runtime.js','./modules/ucos-shell.js','./modules/ucos-v4-integration.js','./modules/ucos-update.js','./modules/ucos-v5-integration.js','./modules/ucos-v6-integration.js','./modules/ucos-jobs.js','./runtime/app-frame.html','./runtime/app-frame.js','./workers/realm-rpc-sw.js','./manifest.webmanifest','./icon.svg'];
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)))});
self.addEventListener('activate',event=>{event.waitUntil((async()=>{for(const k of await caches.keys()){if(k.startsWith('super-api-peer-lab-'))await caches.delete(k);else if(k.startsWith('super-api-ucos-')&&k!==CACHE&&k!==PREVIOUS)await caches.delete(k)}await self.clients.claim()})())});
const JOB_DB='super-api-ucos-sw',JOB_STORE='jobs',SETTINGS_STORE='settings',SUPPORTED_JOB_TYPES=new Set(['notify-clients']),MAX_JOB_BYTES=64*1024,MAX_JOBS=256,JOB_TTL_MS=24*60*60*1000,JOB_LEASE_MS=30000;
let jobDbPromise=null;
function openJobDb(){if(jobDbPromise)return jobDbPromise;jobDbPromise=new Promise((resolve,reject)=>{const r=indexedDB.open(JOB_DB,2);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(JOB_STORE))r.result.createObjectStore(JOB_STORE,{keyPath:'id'});if(!r.result.objectStoreNames.contains(SETTINGS_STORE))r.result.createObjectStore(SETTINGS_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>{jobDbPromise=null;reject(r.error||new Error('job-db-open-failed'))};r.onblocked=()=>{jobDbPromise=null;reject(new Error('job-db-open-blocked'))}});return jobDbPromise}
async function settingGet(key){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SETTINGS_STORE,'readonly'),r=tx.objectStore(SETTINGS_STORE).get(key);r.onsuccess=()=>resolve(r.result??null);r.onerror=()=>reject(r.error)})}
async function settingSet(key,value){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(SETTINGS_STORE,'readwrite');tx.objectStore(SETTINGS_STORE).put(value,key);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function selectedCache(){return(await settingGet('asset-generation').catch(()=>null))==='previous'?PREVIOUS:CACHE}
async function safeCachePut(req,response){try{const cache=await caches.open(CACHE);await cache.put(req,response.clone());return true}catch{return false}}
async function networkFirst(req){try{const response=await fetch(req);if(response.ok)await safeCachePut(req,response);return response}catch(error){const active=await selectedCache(),cached=await caches.open(active).then(c=>c.match(req)).catch(()=>null)||await caches.match(req);if(cached)return cached;throw error}}
self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.origin!==location.origin)return;event.respondWith((async()=>{const active=await selectedCache(),rollback=active===PREVIOUS,cache=await caches.open(active).catch(()=>null);if(req.mode==='navigate'){if(rollback){const old=await cache?.match('./index.html')||await cache?.match('./');if(old)return old}try{const r=await fetch(req);if(r.ok)await safeCachePut('./index.html',r);return r}catch{return await cache?.match('./index.html')||await caches.match('./index.html')||await caches.match('./')}}if(req.destination==='script'||url.pathname.endsWith('.js')){if(rollback){const old=await cache?.match(req);if(old)return old}return networkFirst(req)}const cached=await cache?.match(req);if(cached)return cached;try{const r=await fetch(req);if(r.ok)await safeCachePut(req,r);return r}catch{return await caches.match(req)}})())});
function validateJob(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('invalid-job');const type=String(input.type||'');if(!SUPPORTED_JOB_TYPES.has(type))throw new Error('unsupported-job-type');const id=String(input.id||`job-${Date.now()}-${Math.random().toString(36).slice(2)}`);if(!id||id.length>160)throw new Error('invalid-job-id');const now=Date.now(),job={...input,id,type,queuedAt:now,expiresAt:Math.min(Number(input.expiresAt)||now+JOB_TTL_MS,now+JOB_TTL_MS),status:'queued',attempts:0,leaseUntil:0};let bytes=Infinity;try{bytes=new TextEncoder().encode(JSON.stringify(job)).byteLength}catch{}if(bytes>MAX_JOB_BYTES)throw new Error('job-too-large');return job}
async function getJobs(){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readonly'),r=tx.objectStore(JOB_STORE).getAll();r.onsuccess=()=>resolve(r.result||[]);r.onerror=()=>reject(r.error)})}
async function putJob(job){const db=await openJobDb(),existing=(await getJobs()).find(x=>x.id===job.id),count=(await getJobs()).length;if(!existing&&count>=MAX_JOBS)throw new Error('job-queue-full');return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).put(job);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function updateJob(job){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).put(job);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function deleteJob(id){const db=await openJobDb();return new Promise((resolve,reject)=>{const tx=db.transaction(JOB_STORE,'readwrite');tx.objectStore(JOB_STORE).delete(id);tx.oncomplete=()=>resolve(true);tx.onerror=()=>reject(tx.error)})}
async function drainJobs(){const jobs=(await getJobs()).sort((a,b)=>(a.queuedAt||0)-(b.queuedAt||0)),now=Date.now();let dispatched=0,cleaned=0;for(const job of jobs){if(!SUPPORTED_JOB_TYPES.has(job?.type)||Number(job.expiresAt||0)<=now){await deleteJob(job.id);cleaned++;continue}if(job.status==='dispatched'&&Number(job.leaseUntil||0)>now)continue;const windows=await clients.matchAll({type:'window',includeUncontrolled:true});if(!windows.length)continue;const target=windows.find(w=>w.visibilityState==='visible')||windows[0],next={...job,status:'dispatched',attempts:(Number(job.attempts)||0)+1,lastDispatchedAt:now,leaseUntil:now+JOB_LEASE_MS};await updateJob(next);try{target.postMessage({type:'ucos:background-job',job:next});dispatched++}catch{await updateJob({...next,status:'queued',leaseUntil:0})}}return{dispatched,cleaned,pending:(await getJobs()).length}}
self.addEventListener('sync',event=>{if(event.tag==='super-api-sync'||event.tag==='ucos-jobs')event.waitUntil(drainJobs())});
function realmMembers(obj,maxDepth=6){const seen=new Set(),out=[];let p=obj,depth=0;while(p&&depth++<maxDepth){let keys=[];try{keys=Reflect.ownKeys(p)}catch{break}for(const key of keys){const name=typeof key==='symbol'?key.toString():String(key);if(name==='constructor'||seen.has(name))continue;seen.add(name);let d;try{d=Object.getOwnPropertyDescriptor(p,key)}catch{}out.push({name,kind:typeof d?.value==='function'?'method':(d?.get||d?.set?'accessor':'property'),depth:depth-1})}try{p=Object.getPrototypeOf(p)}catch{break}}return out.sort((a,b)=>a.name.localeCompare(b.name))}
self.addEventListener('message',event=>{const port=event.ports?.[0],data=event.data||{};
 if(data.type==='ucos:activate-update'){self.skipWaiting();port?.postMessage({ok:true,activating:true,cache:CACHE});return}
 if(data.type==='ucos:rollback-assets'){event.waitUntil(settingSet('asset-generation','previous').then(()=>port?.postMessage({ok:true,mode:'previous',cache:PREVIOUS})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})));return}
 if(data.type==='ucos:use-current-assets'){event.waitUntil(settingSet('asset-generation','current').then(()=>port?.postMessage({ok:true,mode:'current',cache:CACHE})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})));return}
 if(data.type==='ucos:cache-status'){event.waitUntil(Promise.all([caches.keys(),selectedCache()]).then(([keys,active])=>port?.postMessage({ok:true,current:CACHE,previous:PREVIOUS,active,caches:keys.filter(k=>k.startsWith('super-api-ucos-'))})));return}
 if(data.type==='super-api-ping'){port?.postMessage({type:'super-api-pong',received:data.time,responded:Date.now(),cache:CACHE});return}
 if(data.type==='super-api-realm-scan'){port?.postMessage({realm:'ServiceWorkerGlobalScope',constructor:self.constructor?.name||null,cache:CACHE,globals:Object.getOwnPropertyNames(self).sort(),members:realmMembers(self),registration:realmMembers(self.registration),clients:realmMembers(self.clients),navigator:realmMembers(self.navigator),caches:realmMembers(self.caches),crypto:realmMembers(self.crypto),performance:realmMembers(self.performance)});return}
 if(data.type==='ucos:queue-job'&&data.job){event.waitUntil((async()=>{try{const job=validateJob(data.job);await putJob(job);port?.postMessage({ok:true,id:job.id})}catch(error){port?.postMessage({ok:false,error:error?.message||String(error)})}})());return}
 if(data.type==='ucos:ack-job'&&data.id){event.waitUntil(deleteJob(String(data.id)).then(()=>port?.postMessage({ok:true,id:String(data.id)})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})));return}
 if(data.type==='ucos:job-status'){event.waitUntil(getJobs().then(jobs=>port?.postMessage({ok:true,pending:jobs.length,maxJobs:MAX_JOBS,ttlMs:JOB_TTL_MS,leaseMs:JOB_LEASE_MS})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})));return}
 if(data.type==='ucos:drain-jobs'){event.waitUntil(drainJobs().then(result=>port?.postMessage({ok:true,...result})).catch(error=>port?.postMessage({ok:false,error:error?.message||String(error)})))}
});
self.addEventListener('notificationclick',event=>{event.notification.close();event.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>ws[0]?.focus()||clients.openWindow('./')))});