const targetUrl=process.argv[2]||'http://127.0.0.1:8767/index.html';
const port=Number(process.argv[3]||9224),sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function target(){for(let i=0;i<200;i++){try{const rows=await fetch(`http://127.0.0.1:${port}/json/list`).then(r=>r.json()),page=rows.find(x=>x.type==='page');if(page?.webSocketDebuggerUrl)return page}catch{}await sleep(100)}throw new Error('CDP target unavailable')}
const t=await target(),ws=new WebSocket(t.webSocketDebuggerUrl),pending=new Map(),exceptions=[];let seq=0;
ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);clearTimeout(p.timer);m.error?p.reject(new Error(m.error.message)):p.resolve(m.result);return}if(m.method==='Runtime.exceptionThrown'){const x=m.params?.exceptionDetails;exceptions.push(x?.exception?.description||x?.text||'runtime-exception')}});
await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('CDP websocket timeout')),10000);ws.addEventListener('open',()=>{clearTimeout(timer);resolve()},{once:true})});
function send(method,params={},timeout=10000){const id=++seq;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error(`${method} timeout`))},timeout);pending.set(id,{resolve,reject,timer});ws.send(JSON.stringify({id,method,params}))})}
async function evalJs(expression,{awaitPromise=false,timeout=10000,userGesture=false}={}){const r=await send('Runtime.evaluate',{expression,awaitPromise,returnByValue:true,userGesture},timeout);if(r.exceptionDetails)throw new Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text||'evaluation failed');return r.result?.value}
try{
 await send('Runtime.enable');await send('Page.enable');await send('Page.navigate',{url:targetUrl});let ready=false;for(let i=0;i<200;i++){try{ready=await evalJs(`Boolean(window.SuperApiLegacyActions&&window.SuperApiUCOS&&window.SuperApiUCOSFunctional&&window.SuperApiUCOSRuntime&&document.querySelector('#ucosOS'))`)}catch{}if(ready)break;await sleep(100)}if(!ready)throw new Error('UCOS functional runtime did not initialize');
 const result=await evalJs(`(async()=>{const sleep=ms=>new Promise(r=>setTimeout(r,ms)),wait=async(fn,label,ms=6000)=>{const start=Date.now();while(Date.now()-start<ms){const v=fn();if(v)return v;await sleep(25)}throw new Error('timeout:'+label)};const Legacy=SuperApiLegacyActions,UCOS=SuperApiUCOS,Functional=SuperApiUCOSFunctional;UCOS.refresh();const primary=Legacy.list();if(primary.length<70)throw new Error('primary-action-count-too-low:'+primary.length);const supported=primary.filter(x=>x.supported!==false),missing=[];for(const x of supported){const cap=UCOS.capabilities.get('action:'+x.id);if(!cap){missing.push(x.id+':catalog');continue}const ps=UCOS.providers.resolve(cap,'execute',{local:true});if(!ps.length)missing.push(x.id+':provider')}if(missing.length)throw new Error('supported-primary-actions-without-provider:'+missing.slice(0,15).join(','));const samples=['encoding','url','file-api','crypto','streams','message-channel','worker','web-storage','dom','geometry'];const executions=[];for(const id of samples){const cap=UCOS.capabilities.get('action:'+id);if(!cap)throw new Error('sample-capability-missing:'+id);const env=await UCOS.execute({capabilityId:cap.id,operation:'execute',args:{},mode:'local'});if(!env.ok||!env.providerId)throw new Error('sample-execution-failed:'+id);executions.push({id,provider:env.providerId})}
 const opener=[...document.querySelectorAll('#ucosOS [data-open-app]')].find(x=>x.dataset.openApp==='capabilities'&&x.isConnected);if(!opener)throw new Error('capability-center-opener-missing');opener.click();const win=await wait(()=>document.querySelector('#ucosOS .ucos-window[data-app-id="capabilities"]'),'capability-window'),select=win.querySelector('#capExec'),op=win.querySelector('#capOp'),mode=win.querySelector('#capMode'),args=win.querySelector('#capArgs'),run=win.querySelector('#capRun'),out=win.querySelector('#capOut');select.value='action:encoding';select.dispatchEvent(new Event('change',{bubbles:true}));mode.value='local';mode.dispatchEvent(new Event('change',{bubbles:true}));await sleep(80);const cap=UCOS.capabilities.get('action:encoding'),expected=cap.operations.length?cap.operations:['execute'],actual=[...op.options].map(x=>x.value);if(JSON.stringify(actual)!==JSON.stringify(expected))throw new Error('capability-operation-ui-mismatch:'+actual.join('|')+' expected '+expected.join('|'));if(run.disabled)throw new Error('supported-capability-run-disabled');args.value='{}';run.click();await wait(()=>out.textContent&&out.textContent!=='No result yet.','capability-result');if(!out.textContent.includes('legacy-main-local'))throw new Error('capability-center-did-not-use-primary-provider');win.querySelector('[data-close]')?.click();
 const legacySelect=document.querySelector('#capabilityOsCapability'),legacyMode=document.querySelector('#capabilityOsMode'),legacyArgs=document.querySelector('#capabilityOsArgs'),legacyRun=document.querySelector('#capabilityOsRun'),legacyOut=document.querySelector('#capabilityOsOut');if(!legacySelect||!legacyRun)throw new Error('legacy-capability-panel-missing');legacySelect.value='action:encoding';legacyMode.value='local';legacyArgs.value='{}';legacyRun.click();await wait(()=>legacyOut.textContent?.includes('legacy-main-local'),'legacy-local-bridge');const health=Functional.health();if(health.primaryProviderCovered<supported.length)throw new Error('functional-health-coverage-mismatch');return{pass:true,primaryActions:primary.length,supportedPrimary:supported.length,providerCoverage:health.primaryProviderCovered,samples:executions,operationContract:actual}})()`,{awaitPromise:true,timeout:45000,userGesture:true});
 if(!result?.pass)throw new Error('functional result missing');if(exceptions.length)throw new Error('uncaught runtime exception(s): '+exceptions.slice(0,3).join(' | '));console.log(JSON.stringify({status:'UCOS_FUNCTIONAL_PASS',...result},null,2));
}finally{try{ws.close()}catch{}}
