'use strict';
const assert=require('node:assert/strict');
const Core=require('../modules/ucos-package-core.js');
assert.equal(Core.compareSemver('1.2.3','1.2.2'),1);
assert.equal(Core.compareSemver('1.2.3','1.2.3'),0);
assert.equal(Core.compareSemver('1.0.0-alpha.2','1.0.0-alpha.10'),-1);
assert.equal(Core.compareSemver('1.0.0','1.0.0-rc.1'),1);
assert.equal(Core.satisfies('6.2.0','>=6.1.0 <7.0.0'),true);
assert.equal(Core.satisfies('7.0.0','^6.0.0'),false);
assert.equal(Core.satisfies('0.2.9','^0.2.3'),true);
assert.equal(Core.satisfies('0.3.0','^0.2.3'),false);
assert.equal(Core.satisfies('0.0.4','^0.0.3'),false);
console.log('UCOS package semantic version matrix passed');
const pkg={format:'ucosapp',formatVersion:1,manifest:{id:'demo.app',name:'Demo',version:'1.0.0',entry:'main.js',capabilities:['action:environment-info']},files:{'main.js':'window.UCOSApp=()=>{};'},minUCOS:'>=6.1.0 <7.0.0'};
const valid=Core.validatePackage(pkg,{ucosVersion:'6.2.0'});assert.equal(valid.valid,true);assert.equal(Core.packageSummary(pkg).files,1);assert.equal(Core.manifestFromPackage(pkg).runtime,'sandbox');
const emptyEntry={...pkg,manifest:{...pkg.manifest,id:'empty.app',entry:'empty.js'},files:{'empty.js':''}};assert.equal(Core.validatePackage(emptyEntry,{ucosVersion:'6.2.0'}).valid,true);
const canonical=Core.normalizePackage({...pkg,manifest:{...pkg.manifest,entry:'./main.js'},files:{'./main.js':'window.UCOSApp=()=>{};','foo..bar.js':'ok'}});assert.equal(canonical.manifest.entry,'main.js');assert.equal(canonical.files['foo..bar.js'],'ok');
console.log('UCOS package validation and manifest conversion passed');
assert.equal(Core.validatePackage({...pkg,format:'zip'},{ucosVersion:'6.2.0'}).valid,false);
assert.equal(Core.validatePackage({...pkg,formatVersion:2},{ucosVersion:'6.2.0'}).valid,false);
assert.equal(Core.validatePackage({...pkg,manifest:{...pkg.manifest,entry:'missing.js'}},{ucosVersion:'6.2.0'}).valid,false);
assert.equal(Core.validatePackage({...pkg,minUCOS:'>=7.0.0'},{ucosVersion:'6.2.0'}).valid,false);
assert.throws(()=>Core.normalizePackage({...pkg,files:{'../escape.js':'x'},manifest:{...pkg.manifest,entry:'../escape.js'}}),/invalid-package-path/);
assert.throws(()=>Core.normalizePackage({...pkg,files:{'a/../../escape.js':'x'},manifest:{...pkg.manifest,entry:'a/../../escape.js'}}),/invalid-package-path/);
const tooMany={};for(let i=0;i<=Core.MAX_FILES;i++)tooMany[`f${i}.js`]='x';assert.throws(()=>Core.normalizePackage({...pkg,files:tooMany}),/package-too-many-files/);
const longPath='x'.repeat(Core.MAX_PATH_BYTES+1)+'.js';assert.throws(()=>Core.normalizePackage({...pkg,manifest:{...pkg.manifest,entry:longPath},files:{[longPath]:'x'}}),/package-path-too-long/);
const hugeManifest={...pkg,manifest:{...pkg.manifest,description:'x'.repeat(Core.MAX_MANIFEST_BYTES+1)}};assert.throws(()=>Core.normalizePackage(hugeManifest),/package-manifest-too-large/);
console.log('UCOS package traversal, limits, empty entry and compatibility rejection passed');
console.log(JSON.stringify({status:'UCOS_PACKAGE_CORE_PASS'},null,2));