(()=>{
'use strict';
let port=null,manifest=null,pid=null,seq=0,appInstance=null;const pending=new Map(),lifecycle=new EventTarget();
function request(service,payload={}){if(!port)return Promise.reject(new Error('UCOS IPC not ready'));const id=`app-${Date.now().toString(36)}-${++seq}`;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('UCOS IPC timeout'))},30000);pending.set(id,{resolve,reject,timer});port.postMessage({type:'request',id,service,...payload})})}
function sdk(){return Object.freeze({
 get manifest(){return manifest},get pid(){return pid},
 capability:Object.freeze({request:(capabilityId,{operation='execute',args={},mode='auto',targetNodeId=''}={})=>request('capability',{capabilityId,operation,args,mode,targetNodeId})}),
 vfs:Object.freeze({stat:path=>request('vfs',{method:'stat',args:[path]}),list:path=>request('vfs',{method:'list',args:[path]}),mkdir:(path,opts)=>request('vfs',{method:'mkdir',args:[path,opts||{}]}),readText:path=>request('vfs',{method:'readText',args:[path]}),writeText:(path,text)=>request('vfs',{method:'writeText',args:[path,text]}),remove:(path,opts)=>request('vfs',{method:'remove',args:[path,opts||{}]}),copy:(a,b)=>request('vfs',{method:'copy',args:[a,b]}),move:(a,b)=>request('vfs',{method:'move',args:[a,b]}),health:()=>request('vfs',{method:'health',args:[]})}),
 workflows:Object.freeze({run:(flow,input)=>request('workflow',{method:'run',args:[flow,input||{}]})}),
 runtime:Object.freeze({health:()=>request('runtime',{method:'health'}),heartbeat:()=>request('runtime',{method:'heartbeat'}),onLifecycle(fn){const h=e=>fn(e.detail);lifecycle.addEventListener('state',h);return()=>lifecycle.removeEventListener('state',h)}})
})}
async function notifyLifecycle(m){lifecycle.dispatchEvent(new CustomEvent('state',{detail:{state:m.state,reason:m.reason,time:m.time}}));try{if(m.state==='suspended'&&typeof appInstance?.onSuspend==='function')await appInstance.onSuspend(m);if(m.state==='running'&&typeof appInstance?.onResume==='function')await appInstance.onResume(m);if(m.state==='crashed'&&typeof appInstance?.onCrash==='function')await appInstance.onCrash(m)}catch(e){port?.postMessage({type:'crash',error:e?.message||String(e)})}}
async function boot(data,p){manifest=data.manifest;pid=data.pid||null;port=p;port.onmessage=e=>{const m=e.data||{};if(m.type==='lifecycle'){notifyLifecycle(m);return}if(m.type!=='response'||!pending.has(m.id))return;const x=pending.get(m.id);pending.delete(m.id);clearTimeout(x.timer);m.ok?x.resolve(m.result):x.reject(new Error(m.error||'UCOS request failed'))};port.start?.();const API=sdk();globalThis.UCOS=API;try{if(!manifest?.entry)throw new Error('App entry missing');const script=document.createElement('script');script.src=new URL(manifest.entry,location.href).href;script.async=true;script.onload=async()=>{try{const app=globalThis.UCOSApp;appInstance=app;if(typeof app==='function')await app(document.querySelector('#app'),API);else if(app&&typeof app.mount==='function')await app.mount(document.querySelector('#app'),API);else throw new Error('App entry must define window.UCOSApp function or {mount()}');port.postMessage({type:'ready'});port.postMessage({type:'heartbeat'})}catch(e){document.querySelector('#app').innerHTML=`<div class="error"></div>`;document.querySelector('.error').textContent=e?.stack||e?.message||String(e);port.postMessage({type:'crash',error:e?.message||String(e)})}};script.onerror=()=>{const err=`Failed to load app entry: ${manifest.entry}`;document.querySelector('#app').innerHTML='<div class="error"></div>';document.querySelector('.error').textContent=err;port.postMessage({type:'crash',error:err})};document.head.appendChild(script)}catch(e){port.postMessage({type:'crash',error:e?.message||String(e)})}}
addEventListener('message',e=>{if(e.data?.type!=='ucos:init'||!e.ports?.[0]||port)return;boot(e.data,e.ports[0])});
document.addEventListener('visibilitychange',()=>port?.postMessage({type:'heartbeat',visibility:document.visibilityState}));
})();
