(()=>{
'use strict';
let port=null,manifest=null,seq=0;const pending=new Map();
function request(service,payload={}){if(!port)return Promise.reject(new Error('UCOS IPC not ready'));const id=`app-${Date.now().toString(36)}-${++seq}`;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error('UCOS IPC timeout'))},30000);pending.set(id,{resolve,reject,timer});port.postMessage({type:'request',id,service,...payload})})}
function sdk(){return Object.freeze({
 get manifest(){return manifest},
 capability:Object.freeze({request:(capabilityId,{operation='execute',args={},mode='auto',targetNodeId=''}={})=>request('capability',{capabilityId,operation,args,mode,targetNodeId})}),
 vfs:Object.freeze({stat:path=>request('vfs',{method:'stat',args:[path]}),list:path=>request('vfs',{method:'list',args:[path]}),mkdir:(path,opts)=>request('vfs',{method:'mkdir',args:[path,opts||{}]}),readText:path=>request('vfs',{method:'readText',args:[path]}),writeText:(path,text)=>request('vfs',{method:'writeText',args:[path,text]}),remove:(path,opts)=>request('vfs',{method:'remove',args:[path,opts||{}]}),copy:(a,b)=>request('vfs',{method:'copy',args:[a,b]}),move:(a,b)=>request('vfs',{method:'move',args:[a,b]}),health:()=>request('vfs',{method:'health',args:[]})}),
 workflows:Object.freeze({run:(flow,input)=>request('workflow',{method:'run',args:[flow,input||{}]}),list:()=>request('workflow',{method:'list',args:[]})})
})}
async function boot(data,p){manifest=data.manifest;port=p;port.onmessage=e=>{const m=e.data||{};if(m.type!=='response'||!pending.has(m.id))return;const x=pending.get(m.id);pending.delete(m.id);clearTimeout(x.timer);m.ok?x.resolve(m.result):x.reject(new Error(m.error||'UCOS request failed'))};port.start?.();const API=sdk();globalThis.UCOS=API;try{if(!manifest?.entry)throw new Error('App entry missing');const script=document.createElement('script');script.src=new URL(manifest.entry,location.href).href;script.async=true;script.onload=async()=>{try{const app=globalThis.UCOSApp;if(typeof app==='function')await app(document.querySelector('#app'),API);else if(app&&typeof app.mount==='function')await app.mount(document.querySelector('#app'),API);else throw new Error('App entry must define window.UCOSApp function or {mount()}');port.postMessage({type:'ready'})}catch(e){document.querySelector('#app').innerHTML=`<div class="error"></div>`;document.querySelector('.error').textContent=e?.stack||e?.message||String(e);port.postMessage({type:'crash',error:e?.message||String(e)})}};script.onerror=()=>{const err=`Failed to load app entry: ${manifest.entry}`;document.querySelector('#app').innerHTML='<div class="error"></div>';document.querySelector('.error').textContent=err;port.postMessage({type:'crash',error:err})};document.head.appendChild(script)}catch(e){port.postMessage({type:'crash',error:e?.message||String(e)})}}
addEventListener('message',e=>{if(e.data?.type!=='ucos:init'||!e.ports?.[0]||port)return;boot(e.data,e.ports[0])});
})();