(()=>{
'use strict';
let port=null,manifest=null,pid=null,seq=0,appInstance=null;const pending=new Map(),lifecycle=new EventTarget(),systemEvents=new EventTarget(),subscriptionRefs=new Map();
const trustedPolicy=globalThis.trustedTypes?.createPolicy?.('ucos-app',{createScriptURL:value=>String(value)})||null;
const parentOrigin=new URL(location.href).origin;
function request(service,payload={},options={}){if(!port)return Promise.reject(new Error('UCOS IPC not ready'));const id=`app-${Date.now().toString(36)}-${++seq}`,signal=options.signal,timeoutMs=Math.max(1000,Math.min(120000,Number(options.timeoutMs)||30000));if(signal?.aborted)return Promise.reject(signal.reason||new DOMException('Aborted','AbortError'));return new Promise((resolve,reject)=>{const finish=(ok,value)=>{const x=pending.get(id);if(!x)return;pending.delete(id);clearTimeout(x.timer);signal?.removeEventListener?.('abort',x.abort);ok?resolve(value):reject(value instanceof Error?value:new Error(String(value)))};const abort=()=>{try{port.postMessage({type:'cancel',id})}catch{}finish(false,signal.reason||new DOMException('Aborted','AbortError'))};const timer=setTimeout(()=>{try{port.postMessage({type:'cancel',id})}catch{}finish(false,new Error('UCOS IPC timeout'))},timeoutMs);pending.set(id,{finish,timer,abort});signal?.addEventListener?.('abort',abort,{once:true});port.postMessage({type:'request',id,service,...payload})})}
function subscribe(type){const name=String(type),count=subscriptionRefs.get(name)||0;subscriptionRefs.set(name,count+1);if(count===0)try{port?.postMessage({type:'subscribe',event:name})}catch{}return name}
function unsubscribe(name){const count=subscriptionRefs.get(name)||0;if(count<=1){subscriptionRefs.delete(name);try{port?.postMessage({type:'unsubscribe',event:name})}catch{}}else subscriptionRefs.set(name,count-1)}
function sdk(){return Object.freeze({
 get manifest(){return manifest},get pid(){return pid},
 capability:Object.freeze({request:(capabilityId,{operation='execute',args={},mode='auto',targetNodeId='',signal=null,timeoutMs=30000}={})=>request('capability',{capabilityId,operation,args,mode,targetNodeId},{signal,timeoutMs})}),
 vfs:Object.freeze({stat:path=>request('vfs',{method:'stat',args:[path]}),list:path=>request('vfs',{method:'list',args:[path]}),mkdir:(path,opts)=>request('vfs',{method:'mkdir',args:[path,opts||{}]}),readText:path=>request('vfs',{method:'readText',args:[path]}),writeText:(path,text)=>request('vfs',{method:'writeText',args:[path,text]}),remove:(path,opts)=>request('vfs',{method:'remove',args:[path,opts||{}]}),copy:(a,b)=>request('vfs',{method:'copy',args:[a,b]}),move:(a,b)=>request('vfs',{method:'move',args:[a,b]}),health:()=>request('vfs',{method:'health',args:[]})}),
 workflows:Object.freeze({run:(flow,input,options={})=>request('workflow',{method:'run',args:[flow,input||{}]},{signal:options.signal,timeoutMs:options.timeoutMs||120000})}),
 runtime:Object.freeze({health:()=>request('runtime',{method:'health'}),heartbeat:()=>request('runtime',{method:'heartbeat'}),onLifecycle(fn){const h=e=>fn(e.detail);lifecycle.addEventListener('state',h);return()=>lifecycle.removeEventListener('state',h)},on(type,fn){const name=subscribe(type),h=e=>fn(e.detail);systemEvents.addEventListener(name,h);let active=true;return()=>{if(!active)return;active=false;systemEvents.removeEventListener(name,h);unsubscribe(name)}}})
})}
function showError(message){const root=document.querySelector('#app'),box=document.createElement('div');box.className='error';box.textContent=String(message||'Unknown sandbox error');root?.replaceChildren(box)}
async function notifyLifecycle(m){lifecycle.dispatchEvent(new CustomEvent('state',{detail:{state:m.state,reason:m.reason,time:m.time}}));try{if(m.state==='suspended'&&typeof appInstance?.onSuspend==='function')await appInstance.onSuspend(m);if(m.state==='running'&&typeof appInstance?.onResume==='function')await appInstance.onResume(m);if(m.state==='crashed'&&typeof appInstance?.onCrash==='function')await appInstance.onCrash(m)}catch(e){port?.postMessage({type:'crash',error:e?.message||String(e)})}}
function scriptUrlFromBoot(data){if(typeof data.entryCode==='string'){const blob=new Blob([data.entryCode],{type:'text/javascript'});return URL.createObjectURL(blob)}if(!manifest?.entry)throw new Error('App entry missing');const rawUrl=new URL(manifest.entry,location.href).href;if(new URL(rawUrl).origin!==parentOrigin)throw new Error('Cross-origin app entry denied');return rawUrl}
async function boot(data,p){manifest=data.manifest;pid=data.pid||null;port=p;port.onmessage=e=>{const m=e.data||{};if(m.type==='lifecycle'){notifyLifecycle(m);return}if(m.type==='event'){systemEvents.dispatchEvent(new CustomEvent(String(m.event||'event'),{detail:m.detail}));return}if(m.type!=='response'||!pending.has(m.id))return;const x=pending.get(m.id);m.ok?x.finish(true,m.result):x.finish(false,new Error(m.error||'UCOS request failed'))};port.start?.();const API=sdk();globalThis.UCOS=API;try{const rawUrl=scriptUrlFromBoot(data),isBlob=rawUrl.startsWith('blob:');const script=document.createElement('script');script.src=trustedPolicy?trustedPolicy.createScriptURL(rawUrl):rawUrl;script.async=true;script.onload=async()=>{try{if(isBlob)URL.revokeObjectURL(rawUrl);const app=globalThis.UCOSApp;appInstance=app;if(typeof app==='function')await app(document.querySelector('#app'),API);else if(app&&typeof app.mount==='function')await app.mount(document.querySelector('#app'),API);else throw new Error('App entry must define window.UCOSApp function or {mount()}');port.postMessage({type:'ready'});port.postMessage({type:'heartbeat'})}catch(e){showError(e?.stack||e?.message||String(e));port.postMessage({type:'crash',error:e?.message||String(e)})}};script.onerror=()=>{if(isBlob)URL.revokeObjectURL(rawUrl);const err=`Failed to load app entry: ${manifest.entry||'package entry'}`;showError(err);port.postMessage({type:'crash',error:err})};document.head.appendChild(script)}catch(e){showError(e?.stack||e?.message||String(e));port.postMessage({type:'crash',error:e?.message||String(e)})}}
addEventListener('message',e=>{if(e.data?.type!=='ucos:init'||!e.ports?.[0]||port||e.source!==parent||e.origin!==parentOrigin)return;boot(e.data,e.ports[0])});
document.addEventListener('visibilitychange',()=>port?.postMessage({type:'heartbeat',visibility:document.visibilityState}));
})();